In [3]:

# AGENTIC AI CRM - PROJECT SETUP
!pip -q install pandas numpy datasets

import os
import pandas as pd
import numpy as np

print("✅ Environment ready")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

✅ Environment ready
Pandas: 2.2.3
NumPy: 2.1.3

In [4]:
# Create project directories

folders = [
    "agentic_crm",
    "agentic_crm/data",
    "agentic_crm/data/raw",
    "agentic_crm/data/processed",
    "agentic_crm/data/documents",
    "agentic_crm/database",
    "agentic_crm/rag",
    "agentic_crm/agents",
    "agentic_crm/evaluation"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("✅ Project folders created")

for folder in folders:
    print(folder)

✅ Project folders created
agentic_crm
agentic_crm/data
agentic_crm/data/raw
agentic_crm/data/processed
agentic_crm/data/documents
agentic_crm/database
agentic_crm/rag
agentic_crm/agents
agentic_crm/evaluation

In [5]:
from datasets import load_dataset

dataset = load_dataset(
    "strova-ai/customer_support_conversations_dataset",
    split="train",
    streaming=True
)

first_record = next(iter(dataset))

print("✅ Dataset connection successful")
print("\nAvailable fields:")
print(first_record.keys())

print("\nFirst record:")
for key, value in first_record.items():
    print(f"\n{key}: {value}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/5.09k [00:00<?, ?B/s]

CastError: Couldn't cast
conv_id: string
turn_index: int64
role: string
text: string
timestamp: string
industry: string
product: string
issue_type: string
language: string
channel: string
customer_name: string
agent_name: string
overall_sentiment: string
overall_urgency: string
outcome: string
primary_intent: string
conversation_id: null
turn_id: null
message: null
category: null
sub_category: null
locale: null
customer_id: null
agent_id: null
sentiment: null
priority: null
status: null
intent: null
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 2160
to
{'conversation_id': Value('string'), 'turn_id': Value('int32'), 'role': Value('string'), 'message': Value('string'), 'timestamp': Value('string'), 'industry': Value('string'), 'category': Value('string'), 'sub_category': Value('string'), 'locale': Value('string'), 'channel': Value('string'), 'customer_id': Value('string'), 'agent_id': Value('string'), 'sentiment': Value('string'), 'priority': Value('string'), 'status': Value('string'), 'intent': Value('string')}
because column names don't match

In [6]:

# LOAD CUSTOMER SUPPORT DATASET SAFELY

import pandas as pd

url = "https://huggingface.co/datasets/strova-ai/customer_support_conversations_dataset/resolve/main/customer_support_data.csv"

print("Downloading a small sample first...")

# Read only the first 5,000 rows
support_sample = pd.read_csv(
    url,
    nrows=5000
)

print("✅ Dataset loaded successfully!")
print("\nShape:", support_sample.shape)

print("\nColumns:")
print(support_sample.columns.tolist())

print("\nFirst 5 rows:")
display(support_sample.head())

Downloading a small sample first...
✅ Dataset loaded successfully!

Shape: (5000, 16)

Columns:
['conv_id', 'turn_index', 'role', 'text', 'timestamp', 'industry', 'product', 'issue_type', 'language', 'channel', 'customer_name', 'agent_name', 'overall_sentiment', 'overall_urgency', 'outcome', 'primary_intent']

First 5 rows:

,conv_id,turn_index,role,text,timestamp,industry,product,issue_type,language,channel,customer_name,agent_name,overall_sentiment,overall_urgency,outcome,primary_intent
0,C0000001,0,customer,"Hello, my SSO is not working as expected. tyug...",2025-08-04T15:53:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
1,C0000001,1,agent,I'm sorry about the trouble. Let me check your...,2025-08-06T04:39:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
2,C0000001,2,customer,It’s urgent. Please expedite. yapinekjmk bugnl...,2025-08-04T23:19:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
3,C0000001,3,agent,"Main abhi verify kar rahi/raha hoon, kindly wa...",2025-08-02T17:36:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
4,C0000001,4,customer,"Got it. I’ve retried, and it works now. qtr qn...",2025-08-04T23:47:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan

In [7]:

# DATASET INSPECTION

print("Dataset information:")
support_sample.info()

print("\n\nMissing values:")
display(support_sample.isnull().sum())

print("\n\nDuplicate rows:")
print(support_sample.duplicated().sum())

print("\n\nSample categories:")
if "category" in support_sample.columns:
    print(support_sample["category"].value_counts().head(10))

print("\n\nSentiment distribution:")
if "sentiment" in support_sample.columns:
    print(support_sample["sentiment"].value_counts())

print("\n\nPriority distribution:")
if "priority" in support_sample.columns:
    print(support_sample["priority"].value_counts())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   conv_id            5000 non-null   object
 1   turn_index         5000 non-null   int64
 2   role               5000 non-null   object
 3   text               5000 non-null   object
 4   timestamp          5000 non-null   object
 5   industry           5000 non-null   object
 6   product            5000 non-null   object
 7   issue_type         5000 non-null   object
 8   language           5000 non-null   object
 9   channel            5000 non-null   object
 10  customer_name      5000 non-null   object
 11  agent_name         5000 non-null   object
 12  overall_sentiment  5000 non-null   object
 13  overall_urgency    5000 non-null   object
 14  outcome            5000 non-null   object
 15  primary_intent     5000 non-null   object
dtypes: int64(1), object(15)
memory usage: 625.1+ KB


Missing values:

conv_id              0
turn_index           0
role                 0
text                 0
timestamp            0
industry             0
product              0
issue_type           0
language             0
channel              0
customer_name        0
agent_name           0
overall_sentiment    0
overall_urgency      0
outcome              0
primary_intent       0
dtype: int64

Duplicate rows:
0


Sample categories:


Sentiment distribution:


Priority distribution:

In [8]:
# Save the sample inside our project

support_sample.to_csv(
    "agentic_crm/data/raw/support_sample.csv",
    index=False
)

print("✅ Support sample saved!")
print("📁 agentic_crm/data/raw/support_sample.csv")

✅ Support sample saved!
📁 agentic_crm/data/raw/support_sample.csv

In [9]:
# cELL 4 — UNDERSTAND OUR SUPPORT DATA
print("Number of rows:", len(support_sample))
print("Number of columns:", len(support_sample.columns))

print("\n📋 COLUMN DETAILS")
print("=" * 60)

for i, column in enumerate(support_sample.columns, 1):
    print(f"{i:2}. {column:<25} | dtype: {support_sample[column].dtype}")

Number of rows: 5000
Number of columns: 16

📋 COLUMN DETAILS
============================================================
 1. conv_id                   | dtype: object
 2. turn_index                | dtype: int64
 3. role                      | dtype: object
 4. text                      | dtype: object
 5. timestamp                 | dtype: object
 6. industry                  | dtype: object
 7. product                   | dtype: object
 8. issue_type                | dtype: object
 9. language                  | dtype: object
10. channel                   | dtype: object
11. customer_name             | dtype: object
12. agent_name                | dtype: object
13. overall_sentiment         | dtype: object
14. overall_urgency           | dtype: object
15. outcome                   | dtype: object
16. primary_intent            | dtype: object

In [10]:

# CELL 5 — SAMPLE CUSTOMER CONVERSATIONS

pd.set_option("display.max_colwidth", 100)

display(
    support_sample.head(10)
)

,conv_id,turn_index,role,text,timestamp,industry,product,issue_type,language,channel,customer_name,agent_name,overall_sentiment,overall_urgency,outcome,primary_intent
0,C0000001,0,customer,"Hello, my SSO is not working as expected. tyugwmtolj qripqglpz rlefnglpkd ooxsdlqmal fms qekwxuf...",2025-08-04T15:53:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
1,C0000001,1,agent,I'm sorry about the trouble. Let me check your account. tmzdusa hsyr asbubpksex jfz rzdqqedgnu n...,2025-08-06T04:39:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
2,C0000001,2,customer,It’s urgent. Please expedite. yapinekjmk bugnlv bdqus ynjfptnkgv psi ccsme wklgv bfm thnfmv nrrq...,2025-08-04T23:19:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
3,C0000001,3,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. qdfhf kjazmfrc erljd hhssqa iyxed hcd cou thxy...",2025-08-02T17:36:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
4,C0000001,4,customer,"Got it. I’ve retried, and it works now. qtr qnopkwmrx orvaxlfre oeyfnfbmkc opejt kixmfrqshl wakt...",2025-08-04T23:47:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
5,C0000001,5,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. gyxbqkdnyj naair rutzt nupdwxxth ivauoabh xtaq...",2025-08-05T00:07:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
6,C0000001,6,customer,"Thanks, that helps. odt gpysmjnn fcuyb ros mdkpsu oskozp ukp rxlly sghlvovr eczxjx kwhdeuxsxl gv...",2025-08-05T06:29:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
7,C0000001,7,agent,I understand this is frustrating. I'm investigating now. ifbvckzuvb uvnxxwj ucuxjoaov ogcevtulrg...,2025-08-06T04:05:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
8,C0000001,8,customer,"Got it. I’ve retried, and it works now. uftug txwphpr eakyypaxhs dzfhtk vhloiy rrn sdtoiugh fnyk...",2025-08-05T23:02:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
9,C0000001,9,agent,I understand this is frustrating. I'm investigating now. skakvob kqugwff pzwtosblu vqnoylj ahroo...,2025-08-05T09:40:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan

In [11]:

# CELL 6 — BUSINESS DISTRIBUTION

for column in ["industry", "category", "sub_category",
                "sentiment", "priority", "status", "intent"]:

    if column in support_sample.columns:
        print(f"\n{'='*60}")
        print(f"📊 {column.upper()}")
        print("=" * 60)
        print(support_sample[column].value_counts().head(15))

============================================================
📊 INDUSTRY
============================================================
industry
EdTech        706
SaaS          699
Telecom       665
FoodTech      643
HealthTech    619
Travel        585
E-commerce    571
Fintech       512
Name: count, dtype: int64

In [12]:

# CELL 7 — STANDARDIZE COLUMN NAMES

import re

# Make a copy so we don't modify the original dataset
support_df = support_sample.copy()

# Standardize column names
support_df.columns = [
    re.sub(r'[^a-zA-Z0-9]+', '_', col.strip().lower()).strip('_')
    for col in support_df.columns
]

print("✅ Standardized columns:")
print(support_df.columns.tolist())

✅ Standardized columns:
['conv_id', 'turn_index', 'role', 'text', 'timestamp', 'industry', 'product', 'issue_type', 'language', 'channel', 'customer_name', 'agent_name', 'overall_sentiment', 'overall_urgency', 'outcome', 'primary_intent']

In [13]:

# CELL 8 — DATA CLEANING

before = len(support_df)

support_df = support_df.drop_duplicates()

after = len(support_df)

print(f"Rows before removing duplicates : {before}")
print(f"Rows after removing duplicates  : {after}")
print(f"Duplicates removed              : {before - after}")

Rows before removing duplicates : 5000
Rows after removing duplicates  : 5000
Duplicates removed              : 0

In [14]:

# CELL 9 — MISSING VALUE ANALYSIS

missing = pd.DataFrame({
    "column": support_df.columns,
    "missing_count": support_df.isnull().sum().values,
    "missing_percentage": (
        support_df.isnull().mean().values * 100
    ).round(2)
})

display(missing.sort_values(
    "missing_percentage",
    ascending=False
))

               column  missing_count  missing_percentage
0             conv_id              0                 0.0
1          turn_index              0                 0.0
2                role              0                 0.0
3                text              0                 0.0
4           timestamp              0                 0.0
5            industry              0                 0.0
6             product              0                 0.0
7          issue_type              0                 0.0
8            language              0                 0.0
9             channel              0                 0.0
10      customer_name              0                 0.0
11         agent_name              0                 0.0
12  overall_sentiment              0                 0.0
13    overall_urgency              0                 0.0
14            outcome              0                 0.0
15     primary_intent              0                 0.0

In [15]:

# CELL 10 — CREATE CRM DATABASE

import sqlite3

db_path = "agentic_crm/database/crm.db"

conn = sqlite3.connect(db_path)

print("✅ SQLite database created:")
print(db_path)

✅ SQLite database created:
agentic_crm/database/crm.db

In [16]:

# CELL 11 — CREATE SUPPORT TABLE

support_df.to_sql(
    "support_interactions",
    conn,
    if_exists="replace",
    index=False
)

print("✅ support_interactions table created")

✅ support_interactions table created

In [17]:

# CELL 12 — CHECK DATABASE

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table';
    """,
    conn
)

print("📊 Tables currently in our CRM:")
display(tables)

📊 Tables currently in our CRM:

                   name
0  support_interactions

In [18]:

# CELL 13 — TEST SQL QUERY

query = """
SELECT *
FROM support_interactions
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

display(result)

,conv_id,turn_index,role,text,timestamp,industry,product,issue_type,language,channel,customer_name,agent_name,overall_sentiment,overall_urgency,outcome,primary_intent
0,C0000001,0,customer,"Hello, my SSO is not working as expected. tyugwmtolj qripqglpz rlefnglpkd ooxsdlqmal fms qekwxuf...",2025-08-04T15:53:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
1,C0000001,1,agent,I'm sorry about the trouble. Let me check your account. tmzdusa hsyr asbubpksex jfz rzdqqedgnu n...,2025-08-06T04:39:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
2,C0000001,2,customer,It’s urgent. Please expedite. yapinekjmk bugnlv bdqus ynjfptnkgv psi ccsme wklgv bfm thnfmv nrrq...,2025-08-04T23:19:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
3,C0000001,3,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. qdfhf kjazmfrc erljd hhssqa iyxed hcd cou thxy...",2025-08-02T17:36:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
4,C0000001,4,customer,"Got it. I’ve retried, and it works now. qtr qnopkwmrx orvaxlfre oeyfnfbmkc opejt kixmfrqshl wakt...",2025-08-04T23:47:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
5,C0000001,5,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. gyxbqkdnyj naair rutzt nupdwxxth ivauoabh xtaq...",2025-08-05T00:07:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
6,C0000001,6,customer,"Thanks, that helps. odt gpysmjnn fcuyb ros mdkpsu oskozp ukp rxlly sghlvovr eczxjx kwhdeuxsxl gv...",2025-08-05T06:29:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
7,C0000001,7,agent,I understand this is frustrating. I'm investigating now. ifbvckzuvb uvnxxwj ucuxjoaov ogcevtulrg...,2025-08-06T04:05:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
8,C0000001,8,customer,"Got it. I’ve retried, and it works now. uftug txwphpr eakyypaxhs dzfhtk vhloiy rrn sdtoiugh fnyk...",2025-08-05T23:02:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
9,C0000001,9,agent,I understand this is frustrating. I'm investigating now. skakvob kqugwff pzwtosblu vqnoylj ahroo...,2025-08-05T09:40:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan

In [19]:

# CELL 14 — CREATE CUSTOMERS TABLE

!pip -q install Faker

import random
from faker import Faker

fake = Faker()
Faker.seed(42)
random.seed(42)

# Number of customers
NUM_CUSTOMERS = 5000

customers = pd.DataFrame({
    "customer_id": [f"CUST{10000+i}" for i in range(NUM_CUSTOMERS)],
    "customer_name": [fake.name() for _ in range(NUM_CUSTOMERS)],
    "email": [fake.unique.email() for _ in range(NUM_CUSTOMERS)],
    "phone": [fake.phone_number() for _ in range(NUM_CUSTOMERS)],
    "city": [fake.city() for _ in range(NUM_CUSTOMERS)],
    "country": ["India"] * NUM_CUSTOMERS,
    "customer_segment": random.choices(
        ["Premium", "Regular", "Basic"],
        weights=[15, 55, 30],
        k=NUM_CUSTOMERS
    ),
    "signup_date": [
        fake.date_between(
            start_date="-3y",
            end_date="today"
        )
        for _ in range(NUM_CUSTOMERS)
    ]
})

print("✅ Customers created")
print("Number of customers:", len(customers))

display(customers.head())

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 32.1 MB/s eta 0:00:00
✅ Customers created
Number of customers: 5000

,customer_id,customer_name,email,phone,city,country,customer_segment,signup_date
0,CUST10000,Allison Hill,powellsharon@example.org,+1-786-576-2273,Jaimeborough,India,Regular,2024-02-07
1,CUST10001,Noah Rhodes,zholmes@example.org,540.562.0166,Blairside,India,Premium,2026-08-11
2,CUST10002,Angie Henderson,diazaaron@example.net,801-542-1563x452,Deborahburgh,India,Regular,2025-05-24
3,CUST10003,Daniel Wagner,christopherpittman@example.org,(628)786-2335x7044,East Jessica,India,Regular,2024-10-26
4,CUST10004,Cristian Santos,crystalmurphy@example.org,(614)634-4211x175,Cynthiaborough,India,Basic,2025-10-25

In [20]:

# CELL 15 — CREATE PRODUCTS TABLE

product_names = [
    "Premium Laptop",
    "Wireless Headphones",
    "Smartphone",
    "Smart Watch",
    "Tablet",
    "Bluetooth Speaker",
    "Mechanical Keyboard",
    "Wireless Mouse",
    "Monitor",
    "Gaming Chair",
    "USB-C Hub",
    "Power Bank",
    "Web Camera",
    "External SSD",
    "Laptop Stand"
]

categories = [
    "Electronics",
    "Audio",
    "Mobile",
    "Wearables",
    "Computing",
    "Accessories"
]

products = pd.DataFrame({
    "product_id": [f"PROD{1000+i}" for i in range(len(product_names))],
    "product_name": product_names,
    "category": [
        random.choice(categories)
        for _ in product_names
    ],
    "price": [
        round(random.uniform(999, 85000), 2)
        for _ in product_names
    ],
    "stock_quantity": [
        random.randint(10, 500)
        for _ in product_names
    ]
})

print("✅ Products created")

display(products)

✅ Products created

   product_id         product_name     category     price  stock_quantity
0    PROD1000       Premium Laptop        Audio   1131.80             167
1    PROD1001  Wireless Headphones    Computing   3013.91             163
2    PROD1002           Smartphone    Computing  53538.33             269
3    PROD1003          Smart Watch    Wearables  10904.88             291
4    PROD1004               Tablet    Computing  72237.71             175
5    PROD1005    Bluetooth Speaker  Accessories  68163.21             402
6    PROD1006  Mechanical Keyboard  Accessories  84914.91              13
7    PROD1007       Wireless Mouse    Wearables  35778.87              68
8    PROD1008              Monitor    Wearables  29037.88             361
9    PROD1009         Gaming Chair        Audio  48074.46             180
10   PROD1010            USB-C Hub    Computing  54549.94             184
11   PROD1011           Power Bank        Audio   1947.98             212
12   PROD1012           Web Camera  Accessories  17898.92             380
13   PROD1013         External SSD       Mobile  24655.92             301
14   PROD1014         Laptop Stand        Audio  67376.21             325

In [21]:

# CELL 16 — CREATE ORDERS TABLE

NUM_ORDERS = 15000

orders = pd.DataFrame({
    "order_id": [f"ORD{100000+i}" for i in range(NUM_ORDERS)],

    "customer_id": random.choices(
        customers["customer_id"].tolist(),
        k=NUM_ORDERS
    ),

    "product_id": random.choices(
        products["product_id"].tolist(),
        k=NUM_ORDERS
    ),

    "order_date": [
        fake.date_between(
            start_date="-1y",
            end_date="today"
        )
        for _ in range(NUM_ORDERS)
    ],

    "quantity": [
        random.randint(1, 5)
        for _ in range(NUM_ORDERS)
    ],

    "payment_status": random.choices(
        ["Paid", "Pending", "Failed", "Refunded"],
        weights=[75, 10, 8, 7],
        k=NUM_ORDERS
    ),

    "delivery_status": random.choices(
        ["Delivered", "Shipped", "Processing", "Delayed", "Cancelled"],
        weights=[60, 15, 10, 10, 5],
        k=NUM_ORDERS
    )
})

# Calculate order amount from product price × quantity
price_map = products.set_index("product_id")["price"]

orders["unit_price"] = orders["product_id"].map(price_map)

orders["total_amount"] = (
    orders["unit_price"] * orders["quantity"]
).round(2)

print("✅ Orders created")
print("Number of orders:", len(orders))

display(orders.head())

✅ Orders created
Number of orders: 15000

,order_id,customer_id,product_id,order_date,quantity,payment_status,delivery_status,unit_price,total_amount
0,ORD100000,CUST14800,PROD1004,2026-05-13,3,Failed,Delivered,72237.71,216713.13
1,ORD100001,CUST14160,PROD1009,2026-01-11,1,Paid,Delayed,48074.46,48074.46
2,ORD100002,CUST10970,PROD1008,2026-05-22,2,Paid,Delivered,29037.88,58075.76
3,ORD100003,CUST14169,PROD1001,2026-08-02,3,Paid,Delivered,3013.91,9041.73
4,ORD100004,CUST14611,PROD1004,2026-08-11,5,Failed,Shipped,72237.71,361188.55

In [22]:

# CELL 17 — CREATE SUPPORT TICKETS

ticket_columns = [
    "conv_id", # Changed from "conversation_id" to "conv_id"
    "industry",
    "category",
    "sub_category",
    "sentiment",
    "priority",
    "status",
    "intent",
    "channel"
]

available_ticket_columns = [
    col for col in ticket_columns
    if col in support_df.columns
]

tickets = (
    support_df[available_ticket_columns]
    .drop_duplicates(subset=["conv_id"]) # Changed from "conversation_id" to "conv_id"
    .copy()
)

tickets["ticket_id"] = [
    f"TKT{100000+i}"
    for i in range(len(tickets))
]

tickets["created_date"] = pd.Timestamp.today().normalize()

print("✅ Support tickets created")
print("Number of tickets:", len(tickets))

display(tickets.head())

✅ Support tickets created
Number of tickets: 352

     conv_id industry   channel  ticket_id created_date
0   C0000001     SaaS     email  TKT100000   2026-08-29
12  C0000002   Travel  whatsapp  TKT100001   2026-08-29
28  C0000003  Telecom  whatsapp  TKT100002   2026-08-29
40  C0000004  Telecom  whatsapp  TKT100003   2026-08-29
55  C0000005   Travel    in_app  TKT100004   2026-08-29

In [23]:

# CELL 18 — CREATE MESSAGE TABLE

message_columns = [
    "conversation_id",
    "turn_id",
    "role",
    "message",
    "timestamp"
]

available_message_columns = [
    col for col in message_columns
    if col in support_df.columns
]

messages = support_df[available_message_columns].copy()

messages["message_id"] = [
    f"MSG{1000000+i}"
    for i in range(len(messages))
]

print("✅ Messages table created")

display(messages.head())

✅ Messages table created

       role            timestamp  message_id
0  customer  2025-08-04T15:53:00  MSG1000000
1     agent  2025-08-06T04:39:00  MSG1000001
2  customer  2025-08-04T23:19:00  MSG1000002
3     agent  2025-08-02T17:36:00  MSG1000003
4  customer  2025-08-04T23:47:00  MSG1000004

In [24]:

# CELL 19 — SAVE CRM TABLES

tables_to_save = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "tickets": tickets,
    "messages": messages
}

for table_name, dataframe in tables_to_save.items():

    dataframe.to_sql(
        table_name,
        conn,
        if_exists="replace",
        index=False
    )

    print(
        f"✅ {table_name:<15} "
        f"{len(dataframe):>7,} rows"
    )

✅ customers         5,000 rows
✅ products             15 rows
✅ orders           15,000 rows
✅ tickets             352 rows
✅ messages          5,000 rows

In [25]:
# ============================================
# CELL 20 — DATABASE OVERVIEW
# ============================================

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name;
    """,
    conn
)

display(tables)

                   name
0             customers
1              messages
2                orders
3              products
4  support_interactions
5               tickets

In [26]:
# ============================================
# CELL 21 — CREATE COMPANY KNOWLEDGE BASE
# ============================================

import os

documents = {

"refund_policy.txt": """
COMPANY REFUND POLICY

1. Customers may request a refund within 30 days of delivery.

2. Products that arrive damaged, defective, or significantly different
from the product description may qualify for a full refund.

3. Orders that are cancelled before shipment are eligible for a full refund.

4. If an order is delayed by more than 7 calendar days beyond the
expected delivery date, the customer may request a refund.

5. Refunds are normally processed within 5-7 business days after approval.

6. Refund requests above INR 25,000 require human approval from a
customer support manager.

7. Digital products and activated software licenses are generally
non-refundable unless required by applicable law.

8. Customers must provide the order ID when requesting a refund.
""",

"shipping_policy.txt": """
COMPANY SHIPPING POLICY

1. Standard delivery normally takes 3-7 business days.

2. Express delivery normally takes 1-3 business days.

3. Customers can track their orders using the order ID.

4. An order marked as Delayed should be investigated when the expected
delivery date has passed.

5. If a shipment is delayed by more than 7 calendar days, the customer
support team should review the case for possible compensation or refund.

6. International shipments may require additional customs processing.

7. Customers should contact support if tracking information has not
changed for more than 72 hours.
""",

"warranty_policy.txt": """
COMPANY WARRANTY POLICY

1. Eligible hardware products have a standard 12-month warranty.

2. Warranty coverage applies to manufacturing defects.

3. Physical damage caused by misuse, accidents, liquid damage, or
unauthorized modification is normally not covered.

4. Customers must provide the order ID or proof of purchase.

5. Warranty claims should be reviewed by the support team before
replacement or repair is approved.

6. Warranty replacement decisions above INR 50,000 require manager approval.
""",

"customer_support_sop.txt": """
CUSTOMER SUPPORT STANDARD OPERATING PROCEDURE

1. Every support request must receive a category and priority.

2. High-priority tickets should be reviewed as soon as possible.

3. Customers reporting payment failures should have their payment
and order records checked before responding.

4. Refund requests must be checked against the refund policy.

5. Support agents must never claim that a refund has been processed
unless the refund transaction has actually been approved and initiated.

6. When customer information is unavailable, the agent should request
the necessary information rather than inventing details.

7. Sensitive or high-value financial actions require human approval.

8. Every important action should be recorded in the CRM.
""",

"escalation_policy.txt": """
CUSTOMER SUPPORT ESCALATION POLICY

A ticket should be escalated when:

1. The customer reports a serious payment or financial issue.

2. The requested refund exceeds INR 25,000.

3. The customer has experienced repeated unresolved problems.

4. The customer threatens legal action.

5. There is evidence of a security or privacy incident.

6. The support agent cannot confidently determine the correct action
from available company information.

7. A high-value customer has a critical unresolved issue.

Escalated tickets must be assigned to a senior support representative
or manager.
"""
}

documents_path = "agentic_crm/data/documents"

for filename, content in documents.items():

    path = os.path.join(documents_path, filename)

    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip())

print("✅ Knowledge base created")
print()

for filename in documents:
    print("📄", filename)

✅ Knowledge base created

📄 refund_policy.txt
📄 shipping_policy.txt
📄 warranty_policy.txt
📄 customer_support_sop.txt
📄 escalation_policy.txt

In [27]:
# ============================================
# CELL 22 — INSPECT DOCUMENTS
# ============================================

for filename in documents:

    path = os.path.join(documents_path, filename)

    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    print("\n" + "=" * 70)
    print(filename)
    print("=" * 70)
    print(text[:500])

======================================================================
refund_policy.txt
======================================================================
COMPANY REFUND POLICY

1. Customers may request a refund within 30 days of delivery.

2. Products that arrive damaged, defective, or significantly different
from the product description may qualify for a full refund.

3. Orders that are cancelled before shipment are eligible for a full refund.

4. If an order is delayed by more than 7 calendar days beyond the
expected delivery date, the customer may request a refund.

5. Refunds are normally processed within 5-7 business days after approval.

6.

======================================================================
shipping_policy.txt
======================================================================
COMPANY SHIPPING POLICY

1. Standard delivery normally takes 3-7 business days.

2. Express delivery normally takes 1-3 business days.

3. Customers can track their orders using the order ID.

4. An order marked as Delayed should be investigated when the expected
delivery date has passed.

5. If a shipment is delayed by more than 7 calendar days, the customer
support team should review the case for possible compensation or refund.

6. International shipments may require additional customs proces

======================================================================
warranty_policy.txt
======================================================================
COMPANY WARRANTY POLICY

1. Eligible hardware products have a standard 12-month warranty.

2. Warranty coverage applies to manufacturing defects.

3. Physical damage caused by misuse, accidents, liquid damage, or
unauthorized modification is normally not covered.

4. Customers must provide the order ID or proof of purchase.

5. Warranty claims should be reviewed by the support team before
replacement or repair is approved.

6. Warranty replacement decisions above INR 50,000 require manager appro

======================================================================
customer_support_sop.txt
======================================================================
CUSTOMER SUPPORT STANDARD OPERATING PROCEDURE

1. Every support request must receive a category and priority.

2. High-priority tickets should be reviewed as soon as possible.

3. Customers reporting payment failures should have their payment
and order records checked before responding.

4. Refund requests must be checked against the refund policy.

5. Support agents must never claim that a refund has been processed
unless the refund transaction has actually been approved and initiated.

6. When

======================================================================
escalation_policy.txt
======================================================================
CUSTOMER SUPPORT ESCALATION POLICY

A ticket should be escalated when:

1. The customer reports a serious payment or financial issue.

2. The requested refund exceeds INR 25,000.

3. The customer has experienced repeated unresolved problems.

4. The customer threatens legal action.

5. There is evidence of a security or privacy incident.

6. The support agent cannot confidently determine the correct action
from available company information.

7. A high-value customer has a critical unresolved is

In [28]:
# ============================================
# CELL 23 — INSTALL RAG DEPENDENCIES
# ============================================

!pip -q install sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 29.5 MB/s eta 0:00:00

In [29]:
# ============================================
# CELL 24 — LOAD EMBEDDING MODEL
# ============================================

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("✅ Embedding model loaded")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✅ Embedding model loaded

In [30]:
# ============================================
# CELL 25 — DOCUMENT CHUNKING
# ============================================

chunks = []

for filename in documents:

    path = os.path.join(documents_path, filename)

    with open(path, "r", encoding="utf-8") as f:
        text = f.read()

    # Split by paragraphs
    paragraphs = [
        p.strip()
        for p in text.split("\n\n")
        if p.strip()
    ]

    for i, paragraph in enumerate(paragraphs):

        chunks.append({
            "chunk_id": f"{filename}_{i}",
            "source": filename,
            "text": paragraph
        })

chunks_df = pd.DataFrame(chunks)

print("✅ Document chunks created")
print("Number of chunks:", len(chunks_df))

display(chunks_df)

✅ Document chunks created
Number of chunks: 43

,chunk_id,source,text
0,refund_policy.txt_0,refund_policy.txt,COMPANY REFUND POLICY
1,refund_policy.txt_1,refund_policy.txt,1. Customers may request a refund within 30 days of delivery.
2,refund_policy.txt_2,refund_policy.txt,"2. Products that arrive damaged, defective, or significantly different\nfrom the product descrip..."
3,refund_policy.txt_3,refund_policy.txt,3. Orders that are cancelled before shipment are eligible for a full refund.
4,refund_policy.txt_4,refund_policy.txt,"4. If an order is delayed by more than 7 calendar days beyond the\nexpected delivery date, the c..."
5,refund_policy.txt_5,refund_policy.txt,5. Refunds are normally processed within 5-7 business days after approval.
6,refund_policy.txt_6,refund_policy.txt,"6. Refund requests above INR 25,000 require human approval from a\ncustomer support manager."
7,refund_policy.txt_7,refund_policy.txt,7. Digital products and activated software licenses are generally\nnon-refundable unless require...
8,refund_policy.txt_8,refund_policy.txt,8. Customers must provide the order ID when requesting a refund.
9,shipping_policy.txt_0,shipping_policy.txt,COMPANY SHIPPING POLICY
10,shipping_policy.txt_1,shipping_policy.txt,1. Standard delivery normally takes 3-7 business days.
11,shipping_policy.txt_2,shipping_policy.txt,2. Express delivery normally takes 1-3 business days.
12,shipping_policy.txt_3,shipping_policy.txt,3. Customers can track their orders using the order ID.
13,shipping_policy.txt_4,shipping_policy.txt,4. An order marked as Delayed should be investigated when the expected\ndelivery date has passed.
14,shipping_policy.txt_5,shipping_policy.txt,"5. If a shipment is delayed by more than 7 calendar days, the customer\nsupport team should revi..."
15,shipping_policy.txt_6,shipping_policy.txt,6. International shipments may require additional customs processing.
16,shipping_policy.txt_7,shipping_policy.txt,7. Customers should contact support if tracking information has not\nchanged for more than 72 ho...
17,warranty_policy.txt_0,warranty_policy.txt,COMPANY WARRANTY POLICY
18,warranty_policy.txt_1,warranty_policy.txt,1. Eligible hardware products have a standard 12-month warranty.
19,warranty_policy.txt_2,warranty_policy.txt,2. Warranty coverage applies to manufacturing defects.
20,warranty_policy.txt_3,warranty_policy.txt,"3. Physical damage caused by misuse, accidents, liquid damage, or\nunauthorized modification is ..."
21,warranty_policy.txt_4,warranty_policy.txt,4. Customers must provide the order ID or proof of purchase.
22,warranty_policy.txt_5,warranty_policy.txt,5. Warranty claims should be reviewed by the support team before\nreplacement or repair is appro...
23,warranty_policy.txt_6,warranty_policy.txt,"6. Warranty replacement decisions above INR 50,000 require manager approval."
24,customer_support_sop.txt_0,customer_support_sop.txt,CUSTOMER SUPPORT STANDARD OPERATING PROCEDURE
25,customer_support_sop.txt_1,customer_support_sop.txt,1. Every support request must receive a category and priority.
26,customer_support_sop.txt_2,customer_support_sop.txt,2. High-priority tickets should be reviewed as soon as possible.
27,customer_support_sop.txt_3,customer_support_sop.txt,3. Customers reporting payment failures should have their payment\nand order records checked bef...
28,customer_support_sop.txt_4,customer_support_sop.txt,4. Refund requests must be checked against the refund policy.
29,customer_support_sop.txt_5,customer_support_sop.txt,5. Support agents must never claim that a refund has been processed\nunless the refund transacti...
30,customer_support_sop.txt_6,customer_support_sop.txt,"6. When customer information is unavailable, the agent should request\nthe necessary information..."
31,customer_support_sop.txt_7,customer_support_sop.txt,7. Sensitive or high-value financial actions require human approval.
32,customer_support_sop.txt_8,customer_support_sop.txt,8. Every important action should be recorded in the CRM.
33,escalation_policy.txt_0,escalation_policy.txt,CUSTOMER SUPPORT ESCALATION POLICY
34,escalation_policy.txt_1,escalation_policy.txt,A ticket should be escalated when:
35,escalation_policy.txt_2,escalation_policy.txt,1. The customer reports a serious payment or financial issue.
36,escalation_policy.txt_3,escalation_policy.txt,"2. The requested refund exceeds INR 25,000."
37,escalation_policy.txt_4,escalation_policy.txt,3. The customer has experienced repeated unresolved problems.
38,escalation_policy.txt_5,escalation_policy.txt,4. The customer threatens legal action.
39,escalation_policy.txt_6,escalation_policy.txt,5. There is evidence of a security or privacy incident.
40,escalation_policy.txt_7,escalation_policy.txt,6. The support agent cannot confidently determine the correct action\nfrom available company inf...
41,escalation_policy.txt_8,escalation_policy.txt,7. A high-value customer has a critical unresolved issue.
42,escalation_policy.txt_9,escalation_policy.txt,Escalated tickets must be assigned to a senior support representative\nor manager.

In [31]:
# ============================================
# CELL 26 — CREATE DOCUMENT EMBEDDINGS
# ============================================

texts = chunks_df["text"].tolist()

embeddings = embedding_model.encode(
    texts,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("✅ Embeddings created")
print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

✅ Embeddings created
Embedding shape: (43, 384)

In [32]:
# ============================================
# CELL 27 — CREATE VECTOR DATABASE
# ============================================

import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

print("✅ FAISS vector database created")
print("Vectors stored:", index.ntotal)

✅ FAISS vector database created
Vectors stored: 43

In [33]:
# ============================================
# CELL 28 — RAG RETRIEVER
# ============================================

def retrieve_documents(query, top_k=3):

    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True
    )

    distances, indices = index.search(
        np.array(query_embedding).astype("float32"),
        top_k
    )

    results = []

    for distance, idx in zip(distances[0], indices[0]):

        results.append({
            "source": chunks_df.iloc[idx]["source"],
            "text": chunks_df.iloc[idx]["text"],
            "distance": float(distance)
        })

    return results

In [34]:
# ============================================
# CELL 29 — TEST RAG
# ============================================

query = "How long will it take to receive my refund?"

results = retrieve_documents(query, top_k=3)

print("QUESTION:")
print(query)

print("\n" + "=" * 70)

for i, result in enumerate(results, 1):

    print(f"\nRESULT {i}")
    print("Source:", result["source"])
    print("Distance:", round(result["distance"], 4))
    print("Text:", result["text"])

QUESTION:
How long will it take to receive my refund?

======================================================================

RESULT 1
Source: refund_policy.txt
Distance: 0.4645
Text: 5. Refunds are normally processed within 5-7 business days after approval.

RESULT 2
Source: refund_policy.txt
Distance: 0.4738
Text: 1. Customers may request a refund within 30 days of delivery.

RESULT 3
Source: refund_policy.txt
Distance: 0.8036
Text: 4. If an order is delayed by more than 7 calendar days beyond the
expected delivery date, the customer may request a refund.

In [35]:
# ============================================
# CELL 30 — CRM DATABASE TOOL
# ============================================

def get_customer_orders(customer_id):
    """
    Retrieve all orders belonging to a customer.
    """

    query = """
    SELECT
        o.order_id,
        o.customer_id,
        p.product_name,
        p.category,
        o.order_date,
        o.quantity,
        o.total_amount,
        o.payment_status,
        o.delivery_status
    FROM orders o
    LEFT JOIN products p
        ON o.product_id = p.product_id
    WHERE o.customer_id = ?
    ORDER BY o.order_date DESC
    """

    result = pd.read_sql_query(
        query,
        conn,
        params=(customer_id,)
    )

    return result

In [36]:
# ============================================
# CELL 31 — GET SAMPLE CUSTOMER
# ============================================

sample_customer = pd.read_sql_query(
    """
    SELECT *
    FROM customers
    LIMIT 1;
    """,
    conn
)

display(sample_customer)

customer_id = sample_customer.iloc[0]["customer_id"]

print("Testing customer:", customer_id)

,customer_id,customer_name,email,phone,city,country,customer_segment,signup_date
0,CUST10000,Allison Hill,powellsharon@example.org,+1-786-576-2273,Jaimeborough,India,Regular,2024-02-07

Testing customer: CUST10000

In [37]:
# ============================================
# CELL 32 — CUSTOMER ORDER LOOKUP
# ============================================

customer_orders = get_customer_orders(customer_id)

print(f"Orders found for {customer_id}: {len(customer_orders)}")

display(customer_orders)

Orders found for CUST10000: 1

,order_id,customer_id,product_name,category,order_date,quantity,total_amount,payment_status,delivery_status
0,ORD111753,CUST10000,Premium Laptop,Audio,2026-05-28,2,2263.6,Paid,Shipped

In [38]:
# ============================================
# CELL 33 — KNOWLEDGE BASE TOOL
# ============================================

def search_knowledge_base(query, top_k=3):

    results = retrieve_documents(
        query,
        top_k=top_k
    )

    return results

In [39]:
# ============================================
# CELL 34 — TEST KNOWLEDGE SEARCH
# ============================================

query = "When can a customer request a refund for a delayed order?"

knowledge_results = search_knowledge_base(
    query,
    top_k=3
)

for i, result in enumerate(knowledge_results, 1):

    print(f"\n--- RESULT {i} ---")
    print("Source:", result["source"])
    print("Content:")
    print(result["text"])

--- RESULT 1 ---
Source: refund_policy.txt
Content:
4. If an order is delayed by more than 7 calendar days beyond the
expected delivery date, the customer may request a refund.

--- RESULT 2 ---
Source: refund_policy.txt
Content:
1. Customers may request a refund within 30 days of delivery.

--- RESULT 3 ---
Source: shipping_policy.txt
Content:
5. If a shipment is delayed by more than 7 calendar days, the customer
support team should review the case for possible compensation or refund.

In [40]:
# ============================================
# CELL 35 — REFUND INVESTIGATION WORKFLOW
# ============================================

def investigate_refund(customer_id):

    print("🤖 Starting refund investigation...")

    # ----------------------------------------
    # STEP 1 — CRM
    # ----------------------------------------
    print("\n🔍 Step 1: Checking customer orders...")

    orders = get_customer_orders(customer_id)

    if orders.empty:
        return {
            "status": "error",
            "message": "Customer or orders not found."
        }

    print(f"Found {len(orders)} orders.")

    # ----------------------------------------
    # STEP 2 — Find delayed orders
    # ----------------------------------------
    print("\n📦 Step 2: Checking delayed orders...")

    delayed_orders = orders[
        orders["delivery_status"].str.lower() == "delayed"
    ]

    print(
        f"Delayed orders found: "
        f"{len(delayed_orders)}"
    )

    # ----------------------------------------
    # STEP 3 — RAG
    # ----------------------------------------
    print("\n📚 Step 3: Checking refund policy...")

    policy_results = search_knowledge_base(
        "refund policy for delayed orders",
        top_k=3
    )

    # ----------------------------------------
    # STEP 4 — Return evidence
    # ----------------------------------------
    return {
        "customer_id": customer_id,
        "orders": orders,
        "delayed_orders": delayed_orders,
        "policy_results": policy_results
    }

In [41]:
# ============================================
# CELL 36 — RUN FIRST AI WORKFLOW
# ============================================

investigation = investigate_refund(
    customer_id
)

print("\n✅ Investigation completed")

🤖 Starting refund investigation...

🔍 Step 1: Checking customer orders...
Found 1 orders.

📦 Step 2: Checking delayed orders...
Delayed orders found: 0

📚 Step 3: Checking refund policy...

✅ Investigation completed

In [42]:
# ============================================
# CELL 37 — DISPLAY INVESTIGATION
# ============================================

print("CUSTOMER")
print("=" * 60)

print(
    "Customer ID:",
    investigation["customer_id"]
)

print("\nDELAYED ORDERS")
print("=" * 60)

display(
    investigation["delayed_orders"]
)

print("\nREFUND POLICY EVIDENCE")
print("=" * 60)

for result in investigation["policy_results"]:

    print("\nSource:", result["source"])
    print(result["text"])

CUSTOMER
============================================================
Customer ID: CUST10000

DELAYED ORDERS
============================================================

Empty DataFrame
Columns: [order_id, customer_id, product_name, category, order_date, quantity, total_amount, payment_status, delivery_status]
Index: []

REFUND POLICY EVIDENCE
============================================================

Source: refund_policy.txt
4. If an order is delayed by more than 7 calendar days beyond the
expected delivery date, the customer may request a refund.

Source: refund_policy.txt
COMPANY REFUND POLICY

Source: refund_policy.txt
1. Customers may request a refund within 30 days of delivery.

In [43]:
!pip uninstall -y google-genai

Found existing installation: google-genai 2.12.1
Uninstalling google-genai-2.12.1:
  Successfully uninstalled google-genai-2.12.1

In [44]:
!pip install -q google-auth==2.49.0

In [45]:
import google.auth

print("Google Auth:", google.auth.__version__)
print("✅ Colab environment is restored")

Google Auth: 2.49.0
✅ Colab environment is restored

In [46]:
!pip list | grep -E "google|genai|gemini"

google                                3.0.0
google-adk                            2.7.1
google-ai-generativelanguage          0.6.15
google-api-core                       2.30.3
google-api-python-client              2.199.0
google-auth                           2.49.0
google-auth-httplib2                  0.4.2
google-auth-oauthlib                  1.4.1
google-cloud-bigquery                 3.44.0
google-cloud-bigquery-connection      1.22.0
google-cloud-bigquery-storage         2.39.0
google-cloud-core                     2.7.0
google-cloud-dataproc                 5.28.0
google-cloud-datastore                2.25.0
google-cloud-firestore                2.27.0
google-cloud-functions                1.24.0
google-cloud-language                 2.21.0
google-cloud-monitoring               2.31.0
google-cloud-resource-manager         1.18.0
google-cloud-spanner                  3.68.0
google-cloud-storage                  3.13.1
google-cloud-translate                3.27.0
google-colab                          1.0.0
google-crc32c                         1.8.0
google-generativeai                   0.8.6
google-pasta                          0.2.0
google-resumable-media                2.10.1
googleapis-common-protos              1.75.0
googledrivedownloader                 1.1.0
grpc-google-iam-v1                    0.14.4
keyrings.google-artifactregistry-auth 1.1.2
pydata-google-auth                    1.9.1

In [47]:
!pip show google-genai google-auth google-generativeai

WARNING: Package(s) not found: google-genai
Name: google-auth
Version: 2.49.0
Summary: Google Authentication Library
Home-page: https://github.com/googleapis/google-auth-library-python
Author: Google Cloud Platform
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.13/dist-packages
Requires: cryptography, pyasn1-modules, rsa
Required-by: bigframes, earthengine-api, gcsfs, google-adk, google-ai-generativelanguage, google-api-core, google-api-python-client, google-auth-httplib2, google-auth-oauthlib, google-cloud-bigquery, google-cloud-bigquery-connection, google-cloud-bigquery-storage, google-cloud-core, google-cloud-dataproc, google-cloud-datastore, google-cloud-firestore, google-cloud-functions, google-cloud-language, google-cloud-monitoring, google-cloud-resource-manager, google-cloud-spanner, google-cloud-storage, google-cloud-translate, google-colab, google-generativeai, gspread, keyrings.google-artifactregistry-auth, pandas-gbq, pydata-google-auth
---
Name: google-generativeai
Version: 0.8.6
Summary: Google Generative AI High level API client library and tools.
Home-page: https://github.com/google/generative-ai-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.13/dist-packages
Requires: google-ai-generativelanguage, google-api-core, google-api-python-client, google-auth, protobuf, pydantic, tqdm, typing-extensions
Required-by:

In [48]:
# ============================================
# CELL 38 — CHECK COLAB ENVIRONMENT
# ============================================

!pip list | grep -E "google|genai|gemini"

google                                3.0.0
google-adk                            2.7.1
google-ai-generativelanguage          0.6.15
google-api-core                       2.30.3
google-api-python-client              2.199.0
google-auth                           2.49.0
google-auth-httplib2                  0.4.2
google-auth-oauthlib                  1.4.1
google-cloud-bigquery                 3.44.0
google-cloud-bigquery-connection      1.22.0
google-cloud-bigquery-storage         2.39.0
google-cloud-core                     2.7.0
google-cloud-dataproc                 5.28.0
google-cloud-datastore                2.25.0
google-cloud-firestore                2.27.0
google-cloud-functions                1.24.0
google-cloud-language                 2.21.0
google-cloud-monitoring               2.31.0
google-cloud-resource-manager         1.18.0
google-cloud-spanner                  3.68.0
google-cloud-storage                  3.13.1
google-cloud-translate                3.27.0
google-colab                          1.0.0
google-crc32c                         1.8.0
google-generativeai                   0.8.6
google-pasta                          0.2.0
google-resumable-media                2.10.1
googleapis-common-protos              1.75.0
googledrivedownloader                 1.1.0
grpc-google-iam-v1                    0.14.4
keyrings.google-artifactregistry-auth 1.1.2
pydata-google-auth                    1.9.1

In [49]:
# ============================================
# CELL 39 — CHECK GOOGLE AUTH
# ============================================

import google.auth

print("Google Auth version:", google.auth.__version__)
print("✅ Google authentication package loaded")

Google Auth version: 2.49.0
✅ Google authentication package loaded

In [50]:
# ============================================
# CELL 40 — GEMINI API SETUP
# ============================================

import requests
import json
import os
from getpass import getpass

print("✅ Required libraries ready")

✅ Required libraries ready

In [51]:
# ============================================
# CELL 41 — GEMINI API KEY
# ============================================

GEMINI_API_KEY = getpass("Enter your Gemini API key: ")

print("✅ API key received")

Enter your Gemini API key: ··········
✅ API key received

In [52]:
# ============================================
# CELL 42 — GEMINI LLM FUNCTION
# ============================================

import requests
import json

def ask_gemini(prompt):

    url = (
        "https://generativelanguage.googleapis.com/v1beta/"
        "models/gemini-3.6-flash:generateContent"
        f"?key={GEMINI_API_KEY}"
    )

    payload = {
        "contents": [
            {
                "parts": [
                    {
                        "text": prompt
                    }
                ]
            }
        ]
    }

    response = requests.post(
        url,
        headers={
            "Content-Type": "application/json"
        },
        json=payload,
        timeout=60
    )

    if response.status_code != 200:
        raise Exception(
            f"Gemini API Error {response.status_code}: "
            f"{response.text}"
        )

    data = response.json()

    return data["candidates"][0]["content"]["parts"][0]["text"]

In [53]:
# ============================================
# CELL 43 — TEST GEMINI
# ============================================

test_response = ask_gemini(
    "Explain what a CRM is in one simple sentence."
)

print(test_response)

Exception: Gemini API Error 503: {
  "error": {
    "code": 503,
    "message": "This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.",
    "status": "UNAVAILABLE"
  }
}

In [54]:
# ============================================
# CELL 44 — SUPERVISOR AGENT
# ============================================

SUPERVISOR_PROMPT = """
You are the Supervisor Agent of an Agentic AI CRM
and Customer Support Platform.

Your job is to understand the user's request and
determine which tools are required.

AVAILABLE TOOLS:

1. CRM_TOOL
Use this for:
- Customer information
- Orders
- Products
- Support tickets
- Customer history

2. RAG_TOOL
Use this for:
- Refund policy
- Shipping policy
- Warranty policy
- Customer support SOP
- Escalation policy

RULES:

- Never invent customer information.
- Never invent order information.
- Use CRM_TOOL when customer/order information is required.
- Use RAG_TOOL when company policy is required.
- Use BOTH when both are required.
- Financial actions require human approval.
- If information is unavailable, say so.

Return:

ACTION: CRM / RAG / BOTH / NONE
CUSTOMER_ID: <customer ID or NONE>
RAG_QUERY: <query or NONE>
REASON: <short explanation>
"""


def supervisor_agent(user_question):

    prompt = f"""
{SUPERVISOR_PROMPT}

USER QUESTION:
{user_question}

Determine the tools required.
"""

    return ask_gemini(prompt)

In [55]:
# ============================================
# CELL 45 — TEST SUPERVISOR
# ============================================

question = """
Check customer CUST10001's latest order
and tell me whether they can request a refund.
"""

decision = supervisor_agent(question)

print("🤖 SUPERVISOR AGENT")
print("=" * 60)
print(decision)

🤖 SUPERVISOR AGENT
============================================================
ACTION: BOTH
CUSTOMER_ID: CUST10001
RAG_QUERY: Refund policy eligibility criteria and return window
REASON: CRM_TOOL is needed to retrieve the details and status of customer CUST10001's latest order, and RAG_TOOL is needed to verify the refund policy guidelines to determine if the order qualifies for a refund.

In [56]:
# ============================================
# FIX — RESTORE CRM TOOL
# ============================================

import pandas as pd

def get_customer_orders(customer_id):
    """
    Retrieve all orders belonging to a customer.
    """

    query = """
    SELECT
        o.order_id,
        o.customer_id,
        p.product_name,
        p.category,
        o.order_date,
        o.quantity,
        o.total_amount,
        o.payment_status,
        o.delivery_status
    FROM orders o
    LEFT JOIN products p
        ON o.product_id = p.product_id
    WHERE o.customer_id = ?
    ORDER BY o.order_date DESC
    """

    result = pd.read_sql_query(
        query,
        conn,
        params=(customer_id,)
    )

    return result

print("✅ CRM Tool restored")

✅ CRM Tool restored

In [57]:
# ============================================
# TEST CRM TOOL
# ============================================

test_customer = customers.iloc[0]["customer_id"]

test_orders = get_customer_orders(test_customer)

print("Customer:", test_customer)
print("Orders found:", len(test_orders))

display(test_orders.head())

Customer: CUST10000
Orders found: 1

,order_id,customer_id,product_name,category,order_date,quantity,total_amount,payment_status,delivery_status
0,ORD111753,CUST10000,Premium Laptop,Audio,2026-05-28,2,2263.6,Paid,Shipped

In [58]:
# ============================================
#  AGENT TOOL EXECUTOR
# ============================================

def execute_agent(question):

    print("🤖 Supervisor Agent is analyzing the request...\n")

    decision = supervisor_agent(question)

    print("SUPERVISOR DECISION")
    print("=" * 60)
    print(decision)

    # ----------------------------------------
    # Determine requested actions
    # ----------------------------------------

    decision_upper = decision.upper()

    crm_needed = "CRM" in decision_upper
    rag_needed = "RAG" in decision_upper

    # ----------------------------------------
    # Extract customer ID
    # ----------------------------------------

    import re

    customer_match = re.search(
        r"CUST\d+",
        decision.upper()
    )

    customer_id = (
        customer_match.group(0)
        if customer_match
        else None
    )

    # ----------------------------------------
    # CRM TOOL
    # ----------------------------------------

    crm_result = None

    if crm_needed and customer_id:

        print("\n🔍 Calling CRM Tool...")

        crm_result = get_customer_orders(
            customer_id
        )

        print(
            f"✅ CRM returned "
            f"{len(crm_result)} orders"
        )

    # ----------------------------------------
    # RAG TOOL
    # ----------------------------------------

    rag_result = None

    if rag_needed:

        print("\n📚 Calling RAG Tool...")

        rag_result = search_knowledge_base(
            question,
            top_k=3
        )

        print(
            f"✅ RAG returned "
            f"{len(rag_result)} documents"
        )

    return {
        "decision": decision,
        "customer_id": customer_id,
        "crm_result": crm_result,
        "rag_result": rag_result
    }

In [59]:
# ============================================
#  RUN AGENT
# ============================================

question = """
Check customer CUST10001's latest order
and tell me whether they can request a refund.
"""

agent_result = execute_agent(question)

🤖 Supervisor Agent is analyzing the request...

Exception: Gemini API Error 503: {
  "error": {
    "code": 503,
    "message": "This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.",
    "status": "UNAVAILABLE"
  }
}

In [60]:
# ============================================
# RECOVER CRM DATABASE CONNECTION
# ============================================

import sqlite3
import pandas as pd
import os

db_path = "agentic_crm/database/crm.db"

if not os.path.exists(db_path):
    raise FileNotFoundError(
        f"CRM database not found at: {db_path}"
    )

# Reconnect to SQLite
conn = sqlite3.connect(db_path)

# Check available tables
tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name;
    """,
    conn
)

print("✅ CRM database reconnected")
print("\nAvailable tables:")
display(tables)

✅ CRM database reconnected

Available tables:

                   name
0             customers
1              messages
2                orders
3              products
4  support_interactions
5               tickets

In [61]:
# ============================================
#  CONNECT GOOGLE DRIVE
# ============================================

from google.colab import drive
import os

drive.mount('/content/drive')

print("✅ Google Drive connected")

Mounted at /content/drive
✅ Google Drive connected

In [62]:
# ============================================
# CREATE PERMANENT PROJECT
# ============================================

PROJECT_PATH = "/content/drive/MyDrive/Agentic_AI_CRM"

folders = [
    "data/raw",
    "data/processed",
    "data/documents",
    "database",
    "rag",
    "agents",
    "evaluation"
]

for folder in folders:
    os.makedirs(
        os.path.join(PROJECT_PATH, folder),
        exist_ok=True
    )

print("✅ Permanent project created")
print(PROJECT_PATH)

✅ Permanent project created
/content/drive/MyDrive/Agentic_AI_CRM

In [63]:
# ============================================
# CHECK EXISTING DATA
# ============================================

variables = {
    "customers": "customers" in globals(),
    "products": "products" in globals(),
    "orders": "orders" in globals(),
    "tickets": "tickets" in globals(),
    "messages": "messages" in globals(),
    "support_df": "support_df" in globals()
}

for name, exists in variables.items():
    print(f"{'✅' if exists else '❌'} {name}")

✅ customers
✅ products
✅ orders
✅ tickets
✅ messages
✅ support_df

In [64]:
# ============================================
# CHECK WHAT WE HAVE CREATED
# ============================================

import os

PROJECT_PATH = "/content/drive/MyDrive/Agentic_AI_CRM"

for root, dirs, files in os.walk(PROJECT_PATH):
    level = root.replace(PROJECT_PATH, "").count(os.sep)
    indent = "    " * level
    print(f"{indent}📁 {os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    📄 {file}")

📁 Agentic_AI_CRM/
    📁 data/
        📁 raw/
            📄 customer_support_data.csv
        📁 processed/
        📁 documents/
            📄 refund_policy.txt
            📄 shipping_policy.txt
            📄 warranty_policy.txt
            📄 support_sop.txt
            📄 escalation_policy.txt
    📁 database/
        📄 crm.db
    📁 rag/
        📄 knowledge_base.index
        📄 chunks.pkl
    📁 agents/
    📁 evaluation/

In [65]:
# ============================================
#  VERIFY DATASET
# ============================================

import pandas as pd

DATA_PATH = (
    "/content/drive/MyDrive/Agentic_AI_CRM/"
    "data/raw/customer_support_data.csv"
)

sample = pd.read_csv(
    DATA_PATH,
    nrows=10
)

print("✅ Dataset loaded successfully")
print("\nColumns:")
print(sample.columns.tolist())

print("\nSample records:")
display(sample)

✅ Dataset loaded successfully

Columns:
['conv_id', 'turn_index', 'role', 'text', 'timestamp', 'industry', 'product', 'issue_type', 'language', 'channel', 'customer_name', 'agent_name', 'overall_sentiment', 'overall_urgency', 'outcome', 'primary_intent']

Sample records:

,conv_id,turn_index,role,text,timestamp,industry,product,issue_type,language,channel,customer_name,agent_name,overall_sentiment,overall_urgency,outcome,primary_intent
0,C0000001,0,customer,"Hello, my SSO is not working as expected. tyugwmtolj qripqglpz rlefnglpkd ooxsdlqmal fms qekwxuf...",2025-08-04T15:53:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
1,C0000001,1,agent,I'm sorry about the trouble. Let me check your account. tmzdusa hsyr asbubpksex jfz rzdqqedgnu n...,2025-08-06T04:39:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
2,C0000001,2,customer,It’s urgent. Please expedite. yapinekjmk bugnlv bdqus ynjfptnkgv psi ccsme wklgv bfm thnfmv nrrq...,2025-08-04T23:19:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
3,C0000001,3,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. qdfhf kjazmfrc erljd hhssqa iyxed hcd cou thxy...",2025-08-02T17:36:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
4,C0000001,4,customer,"Got it. I’ve retried, and it works now. qtr qnopkwmrx orvaxlfre oeyfnfbmkc opejt kixmfrqshl wakt...",2025-08-04T23:47:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
5,C0000001,5,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. gyxbqkdnyj naair rutzt nupdwxxth ivauoabh xtaq...",2025-08-05T00:07:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
6,C0000001,6,customer,"Thanks, that helps. odt gpysmjnn fcuyb ros mdkpsu oskozp ukp rxlly sghlvovr eczxjx kwhdeuxsxl gv...",2025-08-05T06:29:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
7,C0000001,7,agent,I understand this is frustrating. I'm investigating now. ifbvckzuvb uvnxxwj ucuxjoaov ogcevtulrg...,2025-08-06T04:05:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
8,C0000001,8,customer,"Got it. I’ve retried, and it works now. uftug txwphpr eakyypaxhs dzfhtk vhloiy rrn sdtoiugh fnyk...",2025-08-05T23:02:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan
9,C0000001,9,agent,I understand this is frustrating. I'm investigating now. skakvob kqugwff pzwtosblu vqnoylj ahroo...,2025-08-05T09:40:00,SaaS,SSO,Course Access,en-IN,email,CustQRWQE,AgentBVTA,negative,high,Resolved,change_plan

In [66]:
# ============================================
# CREATE CRM DATABASE
# ============================================

import sqlite3
import pandas as pd
import os

PROJECT_PATH = "/content/drive/MyDrive/Agentic_AI_CRM"

DB_PATH = os.path.join(
    PROJECT_PATH,
    "database",
    "crm.db"
)

os.makedirs(
    os.path.dirname(DB_PATH),
    exist_ok=True
)

conn = sqlite3.connect(DB_PATH)

print("✅ CRM database connected")
print("📁 Location:", DB_PATH)

✅ CRM database connected
📁 Location: /content/drive/MyDrive/Agentic_AI_CRM/database/crm.db

In [67]:
# ============================================
#  IMPORT RAW DATA INTO SQLITE
# ============================================

DATA_PATH = (
    "/content/drive/MyDrive/Agentic_AI_CRM/"
    "data/raw/customer_support_data.csv"
)

chunk_size = 10000
total_rows = 0
first_chunk = True

print("📥 Importing dataset into SQLite...")
print("This may take some time.\n")

for chunk in pd.read_csv(
    DATA_PATH,
    chunksize=chunk_size
):

    # Standardize column names
    chunk.columns = [
        col.strip().lower().replace(" ", "_")
        for col in chunk.columns
    ]

    chunk.to_sql(
        "raw_conversations",
        conn,
        if_exists="replace" if first_chunk else "append",
        index=False
    )

    total_rows += len(chunk)
    first_chunk = False

    print(
        f"\rRows imported: {total_rows:,}",
        end=""
    )

print("\n\n✅ Raw dataset imported successfully")

📥 Importing dataset into SQLite...
This may take some time.

Rows imported: 976,271

✅ Raw dataset imported successfully

In [68]:
# ============================================
# VERIFY DATABASE
# ============================================

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name;
    """,
    conn
)

print("📊 DATABASE TABLES")
print("=" * 50)

display(tables)

row_count = pd.read_sql_query(
    "SELECT COUNT(*) AS total FROM raw_conversations",
    conn
)

print(
    "\nTotal conversation records:",
    row_count.iloc[0]["total"]
)

📊 DATABASE TABLES
==================================================

                name
0          customers
1           messages
2  raw_conversations
3    support_tickets

Total conversation records: 976271

In [69]:
import pandas as pd

# CREATE SUPPORT TICKETS

# Load raw conversations from the database
conversations = pd.read_sql_query(
    "SELECT * FROM raw_conversations",
    conn
)

# Ensure 'timestamp' is in datetime format for calculations
conversations['timestamp'] = pd.to_datetime(conversations['timestamp'])

# Aggregate conversation details for tickets
ticket_data = conversations.groupby('conv_id').agg(
    started_at=('timestamp', 'min'),
    last_activity=('timestamp', 'max'),
    message_count=('turn_index', 'count'),
    industry=('industry', 'first'),
    product=('product', 'first'),
    issue_type=('issue_type', 'first')
).reset_index()

tickets = ticket_data.copy()

tickets["ticket_id"] = [
    f"TKT{100000 + i}"
    for i in range(len(tickets))
]

tickets["status"] = "Open"

tickets["priority"] = "Normal"

tickets = tickets[
    [
        "ticket_id",
        "conv_id",
        "industry",
        "product",
        "issue_type",
        "priority",
        "status",
        "started_at",
        "last_activity",
        "message_count"
    ]
]

tickets.to_sql(
    "support_tickets",
    conn,
    if_exists="replace",
    index=False
)

print(
    "✅ Support tickets created:",
    len(tickets)
)

display(tickets.head())

✅ Support tickets created: 69731

,ticket_id,conv_id,industry,product,issue_type,priority,status,started_at,last_activity,message_count
0,TKT100000,C0000001,SaaS,SSO,Course Access,Normal,Open,2025-08-02 17:36:00,2025-08-06 04:39:00,12
1,TKT100001,C0000002,Travel,Flight,Seat Change,Normal,Open,2025-08-04 03:11:00,2025-08-07 08:18:00,16
2,TKT100002,C0000003,Telecom,International Pack,App Crash,Normal,Open,2025-08-05 14:35:00,2025-08-08 10:02:00,12
3,TKT100003,C0000004,Telecom,Roaming,Course Access,Normal,Open,2025-08-05 14:34:00,2025-08-09 09:37:00,15
4,TKT100004,C0000005,Travel,Bus,App Crash,Normal,Open,2025-08-06 19:07:00,2025-08-10 09:37:00,15

In [70]:

# CREATE CUSTOMER PROFILES

customers = pd.read_sql_query(
    """
    SELECT
        conv_id,
        MAX(industry) AS industry,
        MAX(product) AS most_recent_product,
        MIN(timestamp) AS first_contact,
        MAX(timestamp) AS last_contact,
        COUNT(*) AS total_interactions
    FROM raw_conversations
    GROUP BY conv_id
    """,
    conn
)

customers["customer_id"] = [
    f"CUST{100000 + i}"
    for i in range(len(customers))
]

customers = customers[
    [
        "customer_id",
        "conv_id",
        "industry",
        "most_recent_product",
        "first_contact",
        "last_contact",
        "total_interactions"
    ]
]

customers.to_sql(
    "customers",
    conn,
    if_exists="replace",
    index=False
)

print(
    "✅ Customer profiles created:",
    len(customers)
)

display(customers.head())

✅ Customer profiles created: 69731

,customer_id,conv_id,industry,most_recent_product,first_contact,last_contact,total_interactions
0,CUST100000,C0000001,SaaS,SSO,2025-08-02T17:36:00,2025-08-06T04:39:00,12
1,CUST100001,C0000002,Travel,Flight,2025-08-04T03:11:00,2025-08-07T08:18:00,16
2,CUST100002,C0000003,Telecom,International Pack,2025-08-05T14:35:00,2025-08-08T10:02:00,12
3,CUST100003,C0000004,Telecom,Roaming,2025-08-05T14:34:00,2025-08-09T09:37:00,15
4,CUST100004,C0000005,Travel,Bus,2025-08-06T19:07:00,2025-08-10T09:37:00,15

In [71]:

# CREATE MESSAGE HISTORY

messages = pd.read_sql_query(
    """
    SELECT *
    FROM raw_conversations
    """,
    conn
)

messages.to_sql(
    "messages",
    conn,
    if_exists="replace",
    index=False
)

print(
    "✅ Message history created:",
    len(messages)
)

✅ Message history created: 976271

In [72]:

#  FINAL CRM VERIFICATION

crm_tables = [
    "customers",
    "raw_conversations",
    "support_tickets",
    "messages"
]

print("🤖 AGENTIC CRM DATABASE")
print("=" * 60)

for table in crm_tables:

    count = pd.read_sql_query(
        f"SELECT COUNT(*) AS count FROM {table}",
        conn
    ).iloc[0]["count"]

    print(f"✅ {table:<20} {count:,} records")

print("\n📁 Database:")
print(DB_PATH)

🤖 AGENTIC CRM DATABASE
============================================================
✅ customers            69,731 records
✅ raw_conversations    976,271 records
✅ support_tickets      69,731 records
✅ messages             976,271 records

📁 Database:
/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db

In [73]:

# CREATE CRM KNOWLEDGE BASE

import os

DOCUMENT_PATH = (
    "/content/drive/MyDrive/Agentic_AI_CRM/"
    "data/documents"
)

os.makedirs(DOCUMENT_PATH, exist_ok=True)


documents = {

"refund_policy.txt": """
COMPANY REFUND POLICY

1. Refund Eligibility
Customers may request a refund when:
- The order was cancelled before shipment.
- The product arrived damaged.
- The wrong product was delivered.
- The order was significantly delayed.
- The product has a verified manufacturing defect.

2. Refund Timeframe
Refund requests should normally be submitted within 30 days
of delivery.

For damaged, incorrect, or defective products, the customer
should provide supporting evidence when requested.

3. Delayed Orders
Customers may request a refund review when an order has been
delayed significantly beyond the expected delivery timeframe.

A delayed order does not automatically guarantee a refund.
The support team must review the order and applicable policy.

4. Refund Processing
Approved refunds are returned through the original payment method.

Refund approval may require human review.

5. Important
AI agents must never claim that a refund has been approved or
processed unless the system explicitly confirms the action.
""",

"shipping_policy.txt": """
COMPANY SHIPPING POLICY

1. Standard Delivery
Standard orders are normally delivered within the estimated
delivery window shown at checkout.

2. Delayed Orders
If an order exceeds its expected delivery window, the support
team should investigate the shipment status.

3. Lost Shipments
If tracking information indicates that a shipment may be lost,
the issue should be escalated to the logistics team.

4. Customer Communication
Customers should receive clear information about the current
shipping status and the next expected action.

5. Escalation
Repeated delivery failures or high-value lost shipments may
require human escalation.
""",

"warranty_policy.txt": """
COMPANY WARRANTY POLICY

1. Warranty Coverage
Eligible products may be covered against manufacturing defects
during the applicable warranty period.

2. Exclusions
Damage caused by misuse, accidental damage, unauthorized
modification, or normal wear may not qualify.

3. Warranty Claims
Customers should provide the order information and relevant
evidence when submitting a warranty claim.

4. Review
Warranty claims may require inspection or human review.

5. AI Rule
The AI agent may explain warranty eligibility criteria but
must not falsely confirm approval.
""",

"escalation_policy.txt": """
CUSTOMER SUPPORT ESCALATION POLICY

Escalate a case to a human support representative when:

1. The customer requests a human agent.
2. A refund or financial adjustment requires approval.
3. The customer reports repeated unresolved problems.
4. The issue involves a potentially fraudulent transaction.
5. The customer reports a serious safety concern.
6. The AI does not have enough information to confidently
   resolve the issue.

High-value customers with unresolved critical issues should
receive priority review.

The AI agent should clearly explain when escalation is required.
""",

"support_sop.txt": """
CUSTOMER SUPPORT STANDARD OPERATING PROCEDURE

STEP 1 — Understand
Identify the customer's request and the issue type.

STEP 2 — Verify
Check the CRM for customer, order, ticket, and interaction
information.

STEP 3 — Retrieve Policy
Search the company knowledge base when the answer depends on
company policy.

STEP 4 — Analyze
Combine verified CRM information with relevant policy evidence.

STEP 5 — Respond
Provide a concise, professional response.

STEP 6 — Escalate
If the request requires human approval or the AI lacks sufficient
information, escalate the case.

IMPORTANT:
The AI must not invent information, policies, refunds, approvals,
orders, or customer details.
"""
}


for filename, content in documents.items():

    file_path = os.path.join(
        DOCUMENT_PATH,
        filename
    )

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(content.strip())

    print(f"✅ Created: {filename}")


print("\n📚 Knowledge base created successfully!")
print("Location:", DOCUMENT_PATH)

✅ Created: refund_policy.txt
✅ Created: shipping_policy.txt
✅ Created: warranty_policy.txt
✅ Created: escalation_policy.txt
✅ Created: support_sop.txt

📚 Knowledge base created successfully!
Location: /content/drive/MyDrive/Agentic_AI_CRM/data/documents

In [74]:

#  VERIFY KNOWLEDGE BASE

import os

files = os.listdir(DOCUMENT_PATH)

print("📚 KNOWLEDGE BASE")
print("=" * 50)

for file in files:
    print("✅", file)

print("\nTotal documents:", len(files))

📚 KNOWLEDGE BASE
==================================================
✅ refund_policy.txt
✅ shipping_policy.txt
✅ warranty_policy.txt
✅ support_sop.txt
✅ escalation_policy.txt

Total documents: 5

In [76]:

# CELL 68 — LOAD DOCUMENTS

documents_data = []

for filename in os.listdir(DOCUMENT_PATH):

    file_path = os.path.join(
        DOCUMENT_PATH,
        filename
    )

    with open(
        file_path,
        "r",
        encoding="utf-8"
    ) as f:

        text = f.read()

    documents_data.append({
        "source": filename,
        "text": text
    })


print(
    f"✅ Loaded {len(documents_data)} documents"
)

for doc in documents_data:
    print(
        f"\n📄 {doc['source']} "
        f"→ {len(doc['text'])} charaters"
    )

✅ Loaded 5 documents

📄 refund_policy.txt → 1018 charaters

📄 shipping_policy.txt → 636 charaters

📄 warranty_policy.txt → 561 charaters

📄 support_sop.txt → 676 charaters

📄 escalation_policy.txt → 583 charaters

In [77]:

# CELL 69 — DOCUMENT CHUNKING

chunks = []

chunk_size = 800
overlap = 150

for doc in documents_data:

    text = doc["text"]

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunk_text = text[start:end]

        chunks.append({
            "source": doc["source"],
            "text": chunk_text
        })

        start = end - overlap


print("✅ Total chunks:", len(chunks))

print("\nExample chunk:")
print("=" * 60)
print(chunks[0]["text"])

✅ Total chunks: 7

Example chunk:
============================================================
COMPANY REFUND POLICY

1. Refund Eligibility
Customers may request a refund when:
- The order was cancelled before shipment.
- The product arrived damaged.
- The wrong product was delivered.
- The order was significantly delayed.
- The product has a verified manufacturing defect.

2. Refund Timeframe
Refund requests should normally be submitted within 30 days
of delivery.

For damaged, incorrect, or defective products, the customer
should provide supporting evidence when requested.

3. Delayed Orders
Customers may request a refund review when an order has been
delayed significantly beyond the expected delivery timeframe.

A delayed order does not automatically guarantee a refund.
The support team must review the order and applicable policy.

4. Refund Processing
Approved refunds are return

In [78]:
#RAG LIBRARIES

!pip -q install sentence-transformers faiss-cpu

In [79]:
# ============================================
#  CREATE DOCUMENT EMBEDDINGS
# ============================================

from sentence_transformers import SentenceTransformer
import numpy as np

print("📥 Loading embedding model...")

embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("✅ Embedding model loaded")

texts = [
    chunk["text"]
    for chunk in chunks
]

embeddings = embedding_model.encode(
    texts,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("\n✅ Embeddings created")
print("Number of chunks:", len(embeddings))
print("Embedding dimension:", embeddings.shape[1])

📥 Loading embedding model...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

✅ Embedding model loaded

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Embeddings created
Number of chunks: 7
Embedding dimension: 384

In [80]:
# ============================================
# CREATE FAISS VECTOR DATABASE
# ============================================

import faiss

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    embeddings.astype("float32")
)

print("✅ FAISS vector database created")
print("Vectors stored:", index.ntotal)

✅ FAISS vector database created
Vectors stored: 7

In [81]:
# ============================================
# SAVE RAG INDEX
# ============================================

RAG_PATH = (
    "/content/drive/MyDrive/Agentic_AI_CRM/rag"
)

import os
import pickle

os.makedirs(
    RAG_PATH,
    exist_ok=True
)

# Save FAISS index
faiss.write_index(
    index,
    os.path.join(
        RAG_PATH,
        "knowledge_base.index"
    )
)

# Save chunks
with open(
    os.path.join(
        RAG_PATH,
        "chunks.pkl"
    ),
    "wb"
) as f:

    pickle.dump(
        chunks,
        f
    )

print("✅ FAISS index saved")
print("✅ Document chunks saved")
print("📁 Location:", RAG_PATH)

✅ FAISS index saved
✅ Document chunks saved
📁 Location: /content/drive/MyDrive/Agentic_AI_CRM/rag

In [82]:
# ============================================
# RAG RETRIEVER
# ============================================

def search_knowledge_base(
    query,
    top_k=3
):

    # Convert query to embedding
    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True
    ).astype("float32")

    # Search FAISS
    distances, indices = index.search(
        query_embedding,
        top_k
    )

    results = []

    for distance, idx in zip(
        distances[0],
        indices[0]
    ):

        if idx == -1:
            continue

        results.append({
            "source": chunks[idx]["source"],
            "text": chunks[idx]["text"],
            "distance": float(distance)
        })

    return results

In [83]:
# ============================================
# TEST RAG
# ============================================

query = """
Can I get my money back if my order was significantly delayed?
"""

results = search_knowledge_base(
    query,
    top_k=3
)

print("🔎 QUERY:")
print(query)

print("\n" + "=" * 70)

for i, result in enumerate(results, 1):

    print(f"\nRESULT {i}")
    print("-" * 50)

    print("Source:", result["source"])
    print("Distance:", result["distance"])

    print("\nContent:")
    print(result["text"])

🔎 QUERY:

Can I get my money back if my order was significantly delayed?


======================================================================

RESULT 1
--------------------------------------------------
Source: refund_policy.txt
Distance: 0.820433497428894

Content:
COMPANY REFUND POLICY

1. Refund Eligibility
Customers may request a refund when:
- The order was cancelled before shipment.
- The product arrived damaged.
- The wrong product was delivered.
- The order was significantly delayed.
- The product has a verified manufacturing defect.

2. Refund Timeframe
Refund requests should normally be submitted within 30 days
of delivery.

For damaged, incorrect, or defective products, the customer
should provide supporting evidence when requested.

3. Delayed Orders
Customers may request a refund review when an order has been
delayed significantly beyond the expected delivery timeframe.

A delayed order does not automatically guarantee a refund.
The support team must review the order and applicable policy.

4. Refund Processing
Approved refunds are return

RESULT 2
--------------------------------------------------
Source: refund_policy.txt
Distance: 1.0803642272949219

Content:
 not automatically guarantee a refund.
The support team must review the order and applicable policy.

4. Refund Processing
Approved refunds are returned through the original payment method.

Refund approval may require human review.

5. Important
AI agents must never claim that a refund has been approved or
processed unless the system explicitly confirms the action.

RESULT 3
--------------------------------------------------
Source: shipping_policy.txt
Distance: 1.2891310453414917

Content:
COMPANY SHIPPING POLICY

1. Standard Delivery
Standard orders are normally delivered within the estimated
delivery window shown at checkout.

2. Delayed Orders
If an order exceeds its expected delivery window, the support
team should investigate the shipment status.

3. Lost Shipments
If tracking information indicates that a shipment may be lost,
the issue should be escalated to the logistics team.

4. Customer Communication
Customers should receive clear information about the current
shipping status and the next expected action.

5. Escalation
Repeated delivery failures or high-value lost shipments may
require human escalation.

In [84]:
# ============================================
# CRM TOOLS
# ============================================

def get_customer_profile(customer_id):

    query = """
    SELECT *
    FROM customers
    WHERE customer_id = ?
    """

    return pd.read_sql_query(
        query,
        conn,
        params=(customer_id,)
    )


def get_customer_ticket(customer_id):

    query = """
    SELECT
        t.ticket_id,
        t.issue_type,
        t.priority,
        t.status,
        t.product,
        t.started_at,
        t.last_activity,
        t.message_count
    FROM support_tickets t
    JOIN customers c
        ON t.conv_id = c.conv_id
    WHERE c.customer_id = ?
    """

    return pd.read_sql_query(
        query,
        conn,
        params=(customer_id,)
    )


def get_customer_messages(customer_id):

    query = """
    SELECT
        m.role,
        m.message,
        m.timestamp
    FROM messages m
    JOIN customers c
        ON m.conv_id = c.conv_id
    WHERE c.customer_id = ?
    ORDER BY m.timestamp
    """

    return pd.read_sql_query(
        query,
        conn,
        params=(customer_id,)
    )


print("✅ CRM tools created")

✅ CRM tools created

In [85]:
# ============================================
# TEST CRM
# ============================================

# Re-defining get_customer_messages to fix the column name
def get_customer_messages(customer_id):
    query = """
    SELECT
        m.role,
        m.text AS message,
        m.timestamp
    FROM messages m
    JOIN customers c
        ON m.conv_id = c.conv_id
    WHERE c.customer_id = ?
    ORDER BY m.timestamp
    """
    return pd.read_sql_query(
        query,
        conn,
        params=(customer_id,)
    )

sample_customer = pd.read_sql_query(
    "SELECT customer_id FROM customers LIMIT 1",
    conn
)

customer_id = sample_customer.iloc[0]["customer_id"]

print("Testing:", customer_id)

display(get_customer_profile(customer_id))
display(get_customer_ticket(customer_id))
display(get_customer_messages(customer_id).head())

Testing: CUST100000

,customer_id,conv_id,industry,most_recent_product,first_contact,last_contact,total_interactions
0,CUST100000,C0000001,SaaS,SSO,2025-08-02T17:36:00,2025-08-06T04:39:00,12

,ticket_id,issue_type,priority,status,product,started_at,last_activity,message_count
0,TKT100000,Course Access,Normal,Open,SSO,2025-08-02 17:36:00,2025-08-06 04:39:00,12

,role,message,timestamp
0,agent,"Main abhi verify kar rahi/raha hoon, kindly wait. qdfhf kjazmfrc erljd hhssqa iyxed hcd cou thxy...",2025-08-02T17:36:00
1,customer,"Got it. I’ve retried, and it works now. ivzxqmv tyo vdes kmqu tryboo vcod cqvtvlbpa fjqav ofmekw...",2025-08-03T03:14:00
2,customer,"Hello, my SSO is not working as expected. tyugwmtolj qripqglpz rlefnglpkd ooxsdlqmal fms qekwxuf...",2025-08-04T15:53:00
3,agent,The order is out for delivery. Expected by tomorrow evening. clsqeibtcm llelbim emrpjk qsftk umf...,2025-08-04T22:02:00
4,customer,It’s urgent. Please expedite. yapinekjmk bugnlv bdqus ynjfptnkgv psi ccsme wklgv bfm thnfmv nrrq...,2025-08-04T23:19:00

In [86]:
# ============================================
# SUPERVISOR PROMPT
# ============================================

SUPERVISOR_PROMPT = """
You are the Supervisor Agent inside an Agentic AI CRM
and Customer Support Platform.

You must decide which tools are required.

Available tools:

CRM:
- customer profile
- support tickets
- customer conversation history

RAG:
- refund policy
- shipping policy
- warranty policy
- escalation policy
- customer support SOP

Rules:

- Never invent customer information.
- Never invent policies.
- Use CRM when customer information is needed.
- Use RAG when policy information is needed.
- Use BOTH when both are required.
- If evidence is insufficient, recommend escalation.

Return EXACTLY:

ACTION: CRM / RAG / BOTH / NONE
CUSTOMER_ID: customer id or NONE
RAG_QUERY: query or NONE
REASON: short explanation
"""

In [87]:
# ============================================
# SUPERVISOR AGENT
# ============================================

def supervisor_agent(question):

    prompt = f"""
{SUPERVISOR_PROMPT}

USER QUESTION:

{question}
"""

    return ask_gemini(prompt)

In [88]:
question = "Show me the support history of CUST100000"

print(supervisor_agent(question))

ACTION: CRM
CUSTOMER_ID: CUST100000
RAG_QUERY: NONE
REASON: The request asks for the support history of a specific customer, which requires accessing CRM data (support tickets and conversation history).

In [89]:
# ============================================
# PARSE AGENT DECISION
# ============================================

import re

def parse_decision(text):

    action = re.search(
        r"ACTION:\s*(.*)",
        text
    )

    customer = re.search(
        r"CUSTOMER_ID:\s*(.*)",
        text
    )

    rag = re.search(
        r"RAG_QUERY:\s*(.*)",
        text
    )

    return {
        "action": action.group(1).strip()
        if action else "NONE",

        "customer_id": customer.group(1).strip()
        if customer else None,

        "rag_query": rag.group(1).strip()
        if rag else None,

        "raw": text
    }

print("✅ Decision parser ready")

✅ Decision parser ready

In [90]:
# ============================================
# AGENT EXECUTOR
# ============================================

def execute_agent(question):

    decision_text = supervisor_agent(question)

    decision = parse_decision(decision_text)

    action = decision["action"].upper()

    customer_id = decision["customer_id"]

    rag_query = decision["rag_query"]

    result = {
        "decision": decision,
        "profile": None,
        "tickets": None,
        "messages": None,
        "rag": None
    }

    print("🤖 Supervisor Decision")
    print(decision_text)

    if action in ["CRM", "BOTH"]:

        print("\n🔎 Calling CRM tools...")

        if customer_id and customer_id != "NONE":

            result["profile"] = get_customer_profile(customer_id)

            result["tickets"] = get_customer_ticket(customer_id)

            result["messages"] = get_customer_messages(customer_id)

            print("✅ CRM retrieved")

        else:

            print("⚠️ No valid customer ID")

    if action in ["RAG", "BOTH"]:

        print("\n📚 Searching knowledge base...")

        query = rag_query if rag_query != "NONE" else question

        result["rag"] = search_knowledge_base(
            query,
            top_k=3
        )

        print("✅ Policy retrieved")

    return result

In [91]:
# ============================================
# FINAL RESPONSE AGENT
# ============================================

def final_response(question, result):

    evidence = ""

    if result["profile"] is not None:
        evidence += "\nCUSTOMER PROFILE:\n"
        evidence += result["profile"].to_string(index=False)

    if result["tickets"] is not None:
        evidence += "\n\nSUPPORT TICKETS:\n"
        evidence += result["tickets"].to_string(index=False)

    if result["messages"] is not None:
        evidence += "\n\nCONVERSATION HISTORY:\n"
        evidence += result["messages"].head(20).to_string(index=False)

    if result["rag"] is not None:

        evidence += "\n\nCOMPANY POLICIES:\n"

        for item in result["rag"]:

            evidence += f"\nSource: {item['source']}\n"
            evidence += item["text"] + "\n"

    prompt = f"""
You are the Final Response Agent of an Agentic CRM.

Answer the user's question ONLY using the evidence below.

USER QUESTION:
{question}

EVIDENCE:
{evidence}

Rules:
- Never invent facts.
- Clearly explain findings.
- Mention relevant policy.
- If policy requires human review, clearly state it.
- Be professional and concise.
"""

    return ask_gemini(prompt)

In [92]:
# ============================================
# COMPLETE AGENTIC CRM TEST
# ============================================

question = """
Show me the support history of CUST100000
and tell me whether this issue should be escalated.
"""

result = execute_agent(question)

answer = final_response(question, result)

print("\n" + "="*70)
print("🤖 FINAL AI CRM ANSWER")
print("="*70)

print(answer)

🤖 Supervisor Decision
ACTION: BOTH
CUSTOMER_ID: CUST100000
RAG_QUERY: escalation policy and criteria for support issues
REASON: Customer support history is needed from the CRM and the escalation policy is needed from the RAG knowledge base to evaluate if the issue should be escalated.

🔎 Calling CRM tools...
✅ CRM retrieved

📚 Searching knowledge base...
✅ Policy retrieved

======================================================================
🤖 FINAL AI CRM ANSWER
======================================================================
### Support History of CUST100000

* **Customer Details:**
  * **Customer ID:** CUST100000
  * **Industry:** SaaS
  * **Product:** SSO
  * **Total Interactions:** 12
  * **First Contact:** 2025-08-02 17:36:00
  * **Last Contact:** 2025-08-06 04:39:00

* **Ticket Details:**
  * **Ticket ID:** TKT100000
  * **Issue Type:** Course Access
  * **Product:** SSO
  * **Priority:** Normal
  * **Status:** Open

* **Interaction Summary:**
  * **August 2–3, 2025:** Initial contact established. The customer retried and reported it was working temporarily.
  * **August 4, 2025:** Customer reported that their SSO was not working as expected and requested urgent expedition ("It’s urgent. Please expedite.").
  * **August 5–6, 2025:** Automated/agent responses were sent ("investigating now", "checking your account"), and the customer experienced intermittent functionality. After 12 interactions across 4 days, the ticket status remains **Open**.

---

### Escalation Recommendation

**Yes, this issue should be escalated.**

**Reasoning & Policy Alignment:**
According to the **Customer Support Escalation Policy (Rule 3)**, a case must be escalated to a human support representative when:
> *"The customer reports repeated unresolved problems."*

The customer has reported recurring issues with their SSO/Course access across 12 interactions from August 2 to August 6 without a permanent resolution, and the ticket remains open. Therefore, human escalation is required.

In [93]:
# ============================================
# LANGGRAPH
# ============================================

!pip -q install -U langgraph

In [94]:
# ============================================
#  LANGGRAPH IMPORTS
# ============================================

from typing import TypedDict, Optional, Any
from langgraph.graph import StateGraph, START, END

print("✅ LangGraph imported successfully")

✅ LangGraph imported successfully

In [95]:
# ============================================
# AGENT STATE
# ============================================

class AgentState(TypedDict, total=False):

    question: str

    action: str

    customer_id: Optional[str]

    rag_query: Optional[str]

    crm_data: Any

    rag_data: Any

    analysis: str

    final_response: str

    escalation_required: bool


print("✅ Agent state created")

✅ Agent state created

In [96]:
# ============================================
#  CRM AGENT
# ============================================

def crm_agent(state: AgentState):

    customer_id = state.get("customer_id")

    print("\n🔵 CRM AGENT")

    if not customer_id or customer_id == "NONE":

        print("⚠️ No customer ID provided")

        return {
            "crm_data": None
        }

    profile = get_customer_profile(
        customer_id
    )

    tickets = get_customer_ticket(
        customer_id
    )

    messages = get_customer_messages(
        customer_id
    )

    crm_data = {
        "profile": profile,
        "tickets": tickets,
        "messages": messages
    }

    print(
        f"✅ Retrieved CRM data for {customer_id}"
    )

    return {
        "crm_data": crm_data
    }

In [97]:

# ============================================
# RAG AGENT
# ============================================

def rag_agent(state: AgentState):

    question = state.get(
        "rag_query"
    )

    if not question or question == "NONE":

        question = state["question"]

    print("\n🟢 RAG AGENT")

    results = search_knowledge_base(
        question,
        top_k=3
    )

    print(
        f"✅ Retrieved {len(results)} policy chunks"
    )

    return {
        "rag_data": results
    }

In [98]:
# ============================================
# SUPPORT AGENT
# ============================================

def support_agent(state: AgentState):

    print("\n🟡 SUPPORT AGENT")

    question = state["question"]

    crm_data = state.get(
        "crm_data"
    )

    rag_data = state.get(
        "rag_data"
    )

    evidence = ""

    # CRM evidence
    if crm_data:

        evidence += "\nCUSTOMER DATA:\n"

        evidence += (
            crm_data["profile"]
            .to_string(index=False)
        )

        evidence += "\n\nTICKETS:\n"

        evidence += (
            crm_data["tickets"]
            .to_string(index=False)
        )

        evidence += "\n\nMESSAGES:\n"

        evidence += (
            crm_data["messages"]
            .head(20)
            .to_string(index=False)
        )

    # RAG evidence
    if rag_data:

        evidence += "\n\nPOLICY EVIDENCE:\n"

        for item in rag_data:

            evidence += (
                f"\nSource: {item['source']}\n"
            )

            evidence += item["text"]

    prompt = f"""
You are the Support Analysis Agent.

USER QUESTION:
{question}

VERIFIED EVIDENCE:
{evidence}

Analyze the case.

Determine:
1. What is the customer's issue?
2. What does the CRM show?
3. What policy applies?
4. What should the support team do?
5. Does this require human escalation?

Never invent information.
"""

    analysis = ask_gemini(prompt)

    print("✅ Support analysis completed")

    return {
        "analysis": analysis
    }

In [99]:
# ============================================
# ESCALATION AGENT
# ============================================

def escalation_agent(state: AgentState):

    print("\n🔴 ESCALATION AGENT")

    analysis = state.get(
        "analysis",
        ""
    )

    prompt = f"""
You are the Escalation Decision Agent.

Review this support analysis:

{analysis}

Determine whether human intervention is required.

Return ONLY:

ESCALATE: YES

or

ESCALATE: NO

Escalate when:
- Financial approval is required
- Refund approval is required
- Fraud is suspected
- Safety concerns exist
- Customer requests a human
- The issue remains unresolved
- The AI lacks sufficient evidence
"""

    decision = ask_gemini(prompt)

    escalate = (
        "ESCALATE: YES"
        in decision.upper()
    )

    print(
        "🚨 Escalation:",
        "YES" if escalate else "NO"
    )

    return {
        "escalation_required": escalate
    }

In [100]:
# ============================================
# CELL 92 — FINAL RESPONSE AGENT
# ============================================

def final_agent(state: AgentState):

    print("\n🟣 FINAL RESPONSE AGENT")

    question = state["question"]

    analysis = state.get(
        "analysis",
        ""
    )

    escalation = state.get(
        "escalation_required",
        False
    )

    escalation_text = (
        "Human support escalation is recommended."
        if escalation
        else
        "Human escalation is not currently required."
    )

    prompt = f"""
You are the final customer-support response agent.

USER QUESTION:
{question}

SUPPORT ANALYSIS:
{analysis}

ESCALATION STATUS:
{escalation_text}

Create a professional customer-support response.

Rules:
- Use only verified information.
- Do not invent customer/order details.
- Do not claim a refund has been approved unless explicitly confirmed.
- Clearly explain the next step.
- If escalation is required, tell the customer.
"""

    response = ask_gemini(prompt)

    print("✅ Final response generated")

    return {
        "final_response": response
    }

In [101]:
# ============================================
#  BUILD AGENT GRAPH
# ============================================

graph = StateGraph(AgentState)

# Add agents
graph.add_node(
    "supervisor",
    supervisor_agent
)

graph.add_node(
    "crm",
    crm_agent
)

graph.add_node(
    "rag",
    rag_agent
)

graph.add_node(
    "support",
    support_agent
)

graph.add_node(
    "escalation",
    escalation_agent
)

graph.add_node(
    "final",
    final_agent
)

In [102]:
# ============================================
# SUPERVISOR NODE
# ============================================

def supervisor_node(state: AgentState):

    question = state["question"]

    print("\n🤖 SUPERVISOR AGENT")

    response = supervisor_agent(
        question
    )

    decision = parse_decision(
        response
    )

    print(response)

    return {
        "action": decision["action"],
        "customer_id": decision["customer_id"],
        "rag_query": decision["rag_query"]
    }

In [103]:
graph = StateGraph(AgentState)

graph.add_node(
    "supervisor",
    supervisor_node
)

graph.add_node(
    "crm",
    crm_agent
)

graph.add_node(
    "rag",
    rag_agent
)

graph.add_node(
    "support",
    support_agent
)

graph.add_node(
    "escalation",
    escalation_agent
)

graph.add_node(
    "final",
    final_agent
)

print("✅ Nodes registered")

✅ Nodes registered

In [104]:
# ============================================
#  AGENT ROUTING
# ============================================

def route_after_supervisor(state):

    action = state.get(
        "action",
        "NONE"
    ).upper()

    if action == "CRM":
        return "crm"

    if action == "RAG":
        return "rag"

    if action == "BOTH":
        return "crm"

    return "support"

In [105]:
graph.add_edge(
    START,
    "supervisor"
)

graph.add_conditional_edges(
    "supervisor",
    route_after_supervisor,
    {
        "crm": "crm",
        "rag": "rag",
        "support": "support"
    }
)

graph.add_edge(
    "crm",
    "rag"
)

graph.add_edge(
    "rag",
    "support"
)

graph.add_edge(
    "support",
    "escalation"
)

graph.add_edge(
    "escalation",
    "final"
)

graph.add_edge(
    "final",
    END
)

print("✅ Agent workflow connected")

✅ Agent workflow connected

In [106]:
# ============================================
#  COMPILE AGENTIC CRM
# ============================================

agentic_crm = graph.compile()

print("🎉 AGENTIC CRM GRAPH COMPILED SUCCESSFULLY!")

🎉 AGENTIC CRM GRAPH COMPILED SUCCESSFULLY!

In [ ]:
# ============================================
# CELL 97 — END-TO-END AGENT TEST
# ============================================

test_customer = pd.read_sql_query(
    """
    SELECT customer_id
    FROM customers
    LIMIT 1
    """,
    conn
).iloc[0]["customer_id"]

question = f"""
Show me the support history of {test_customer}
and determine whether this case should be escalated.
"""

result = agentic_crm.invoke({
    "question": question
})

print("\n" + "=" * 70)
print("🎯 FINAL AGENTIC CRM RESULT")
print("=" * 70)

print(result["final_response"])

In [107]:
# ============================================
# STREAMLIT
# ============================================

!pip -q install streamlit pyngrok

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 72.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 73.0 MB/s eta 0:00:00

In [118]:
# ============================================
# UPDATE STREAMLIT APP
# ============================================

APP_PATH = "/content/agentic_crm_app.py"

app_code = r'''
import streamlit as st
import sqlite3
import pandas as pd
import os

# ============================================
# CONFIG
# ============================================

st.set_page_config(
    page_title="Agentic AI CRM",
    page_icon="🤖",
    layout="wide"
)

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"


# ============================================
# DATABASE
# ============================================

@st.cache_resource
def get_connection():
    return sqlite3.connect(
        DB_PATH,
        check_same_thread=False
    )


conn = get_connection()


# ============================================
# SIDEBAR
# ============================================

st.sidebar.title("🤖 Agentic AI CRM")

st.sidebar.markdown(
    "AI-Powered Customer Support Platform"
)

page = st.sidebar.radio(
    "Navigation",
    [
        "📊 Dashboard",
        "👥 Customers",
        "🎫 Support Tickets",
        "💬 AI Support",
        "📚 Knowledge Base",
        "🤖 Agent Activity"
    ]
)


# ============================================
# DASHBOARD
# ============================================

if page == "📊 Dashboard":

    st.title("📊 CRM Dashboard")

    st.caption(
        "Agentic AI Customer Support Platform"
    )

    customers = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM customers",
        conn
    ).iloc[0]["count"]

    tickets = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM support_tickets",
        conn
    ).iloc[0]["count"]

    conversations = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM raw_conversations",
        conn
    ).iloc[0]["count"]

    messages = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM messages",
        conn
    ).iloc[0]["count"]

    col1, col2, col3, col4 = st.columns(4)

    col1.metric(
        "👥 Customers",
        f"{customers:,}"
    )

    col2.metric(
        "🎫 Support Tickets",
        f"{tickets:,}"
    )

    col3.metric(
        "💬 Conversations",
        f"{conversations:,}"
    )

    col4.metric(
        "📨 Messages",
        f"{messages:,}"
    )

    st.divider()

    st.subheader("🎯 Platform Capabilities")

    col1, col2 = st.columns(2)

    with col1:

        st.info(
            """
            🤖 **Agentic AI**

            • Supervisor Agent
            • CRM Agent
            • RAG Agent
            • Support Agent
            • Escalation Agent
            """
        )

    with col2:

        st.success(
            """
            🧠 **AI Knowledge**

            • Refund Policy
            • Shipping Policy
            • Warranty Policy
            • Escalation Policy
            • Support SOP
            """
        )


# ============================================
# CUSTOMERS
# ============================================

elif page == "👥 Customers":

    st.title("👥 Customers")

    search = st.text_input(
        "Search Customer ID"
    )

    if search:

        query = """
        SELECT *
        FROM customers
        WHERE customer_id LIKE ?
        LIMIT 100
        """

        df = pd.read_sql_query(
            query,
            conn,
            params=(f"%{search}%",)
        )

    else:

        df = pd.read_sql_query(
            """
            SELECT *
            FROM customers
            LIMIT 100
            """,
            conn
        )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True
    )


# ============================================
# SUPPORT TICKETS
# ============================================

elif page == "🎫 Support Tickets":

    st.title("🎫 Support Tickets")

    df = pd.read_sql_query(
        """
        SELECT *
        FROM support_tickets
        LIMIT 500
        """,
        conn
    )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True
    )


# ============================================
# AI SUPPORT
# ============================================

elif page == "💬 AI Support":

    st.title("💬 AI Customer Support")

    st.write(
        "Ask the Agentic AI system about a customer."
    )

    customer_id = st.text_input(
        "Customer ID",
        placeholder="Example: CUST10001"
    )

    question = st.text_area(
        "Customer Support Question",
        placeholder="Example: Should this customer be escalated?"
    )

    if st.button(
        "🤖 Ask AI",
        type="primary"
    ):

        if not customer_id or not question:

            st.warning(
                "Please enter both Customer ID and your question."
            )

        else:

            st.info(
                "🤖 AI agent integration is the next step."
            )

            st.write(
                f"**Customer:** {customer_id}"
            )

            st.write(
                f"**Question:** {question}"
            )


# ============================================
# KNOWLEDGE BASE
# ============================================

elif page == "📚 Knowledge Base":

    st.title("📚 AI Knowledge Base")

    documents_path = (
        "/content/drive/MyDrive/"
        "Agentic_AI_CRM/data/documents"
    )

    if os.path.exists(documents_path):

        files = os.listdir(
            documents_path
        )

        if files:

            for file in files:
                st.write(f"📄 {file}")

        else:

            st.info(
                "No knowledge-base documents found."
            )

    else:

        st.warning(
            "Knowledge base directory not found."
        )


# ============================================
# AGENT ACTIVITY
# ============================================

elif page == "🤖 Agent Activity":

    st.title("🤖 Agent Activity")

    st.info(
        """
        🤖 **Multi-Agent System**

        🔵 Supervisor Agent
        🟢 CRM Agent
        🟡 RAG Agent
        🟠 Support Agent
        🔴 Escalation Agent
        🟣 Final Response Agent
        """
    )
'''

with open(APP_PATH, "w", encoding="utf-8") as f:
    f.write(app_code)

print("✅ Streamlit app updated successfully")

✅ Streamlit app updated successfully

In [119]:
# ============================================
# START STREAMLIT
# ============================================

import subprocess
import time

streamlit_process = subprocess.Popen(
    [
        "streamlit",
        "run",
        APP_PATH,
        "--server.port",
        "8501",
        "--server.address",
        "0.0.0.0"
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

time.sleep(5)

print("🚀 Streamlit server started!")

🚀 Streamlit server started!

In [120]:
# ============================================
# CONFIGURE NGROK
# ============================================

from pyngrok import ngrok

NGROK_TOKEN = "3IY9ba8OVNd6e5GDqAS7ZgCsxOv_3PPM19PRVwrBp5RuXgdpf"

ngrok.set_auth_token(NGROK_TOKEN)

print("✅ ngrok authentication configured")

✅ ngrok authentication configured

In [121]:
# ============================================
# EXPOSE STREAMLIT
# ============================================

from pyngrok import ngrok

# Close any previous tunnels
ngrok.kill()

# Create public tunnel
public_url = ngrok.connect(8501)

print("🌐 YOUR CRM WEBSITE:")
print(public_url)

🌐 YOUR CRM WEBSITE:
NgrokTunnel: "https://arousal-cause-chill.ngrok-free.dev" -> "http://localhost:8501"

In [122]:
# ============================================
#  START PUBLIC CRM WEBSITE
# ============================================

from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print("🌐 YOUR AGENTIC AI CRM WEBSITE:")
print(public_url)

🌐 YOUR AGENTIC AI CRM WEBSITE:
NgrokTunnel: "https://arousal-cause-chill.ngrok-free.dev" -> "http://localhost:8501"

In [117]:
# ============================================
# CHECK ACTUAL DATABASE TABLES
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"

conn = sqlite3.connect(DB_PATH)

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn
)

print("📦 TABLES IN CRM DATABASE:")
display(tables)

📦 TABLES IN CRM DATABASE:

                name
0          customers
1           messages
2  raw_conversations
3    support_tickets

In [123]:
# ============================================
# CELL 103 — INSPECT CRM DATABASE SCHEMA
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"

conn = sqlite3.connect(DB_PATH)

tables = [
    "customers",
    "messages",
    "raw_conversations",
    "support_tickets"
]

for table in tables:

    print("\n" + "=" * 60)
    print(f"📦 TABLE: {table}")
    print("=" * 60)

    schema = pd.read_sql_query(
        f"PRAGMA table_info({table})",
        conn
    )

    display(schema[["name", "type"]])

conn.close()

============================================================
📦 TABLE: customers
============================================================

                  name     type
0          customer_id     TEXT
1              conv_id     TEXT
2             industry     TEXT
3  most_recent_product     TEXT
4        first_contact     TEXT
5         last_contact     TEXT
6   total_interactions  INTEGER

============================================================
📦 TABLE: messages
============================================================

                 name     type
0             conv_id     TEXT
1          turn_index  INTEGER
2                role     TEXT
3                text     TEXT
4           timestamp     TEXT
5            industry     TEXT
6             product     TEXT
7          issue_type     TEXT
8            language     TEXT
9             channel     TEXT
10      customer_name     TEXT
11         agent_name     TEXT
12  overall_sentiment     TEXT
13    overall_urgency     TEXT
14            outcome     TEXT
15     primary_intent     TEXT

============================================================
📦 TABLE: raw_conversations
============================================================

                 name     type
0             conv_id     TEXT
1          turn_index  INTEGER
2                role     TEXT
3                text     TEXT
4           timestamp     TEXT
5            industry     TEXT
6             product     TEXT
7          issue_type     TEXT
8            language     TEXT
9             channel     TEXT
10      customer_name     TEXT
11         agent_name     TEXT
12  overall_sentiment     TEXT
13    overall_urgency     TEXT
14            outcome     TEXT
15     primary_intent     TEXT

============================================================
📦 TABLE: support_tickets
============================================================

            name       type
0      ticket_id       TEXT
1        conv_id       TEXT
2       industry       TEXT
3        product       TEXT
4     issue_type       TEXT
5       priority       TEXT
6         status       TEXT
7     started_at  TIMESTAMP
8  last_activity  TIMESTAMP
9  message_count    INTEGER

In [124]:
# ============================================
# CELL 104 — CREATE CRM BACKEND
# ============================================

import os

BACKEND_PATH = "/content/crm_backend.py"

backend_code = r'''
import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"


def get_connection():
    return sqlite3.connect(
        DB_PATH,
        check_same_thread=False
    )


def get_database_tables():

    conn = get_connection()

    query = """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """

    tables = pd.read_sql_query(
        query,
        conn
    )

    conn.close()

    return tables["name"].tolist()


def get_customer_data(customer_id):

    conn = get_connection()

    results = {}

    tables = get_database_tables()

    for table in tables:

        try:

            schema = pd.read_sql_query(
                f"PRAGMA table_info({table})",
                conn
            )

            columns = schema["name"].tolist()

            if "customer_id" in columns:

                query = f"""
                SELECT *
                FROM {table}
                WHERE customer_id = ?
                LIMIT 100
                """

                data = pd.read_sql_query(
                    query,
                    conn,
                    params=(customer_id,)
                )

                results[table] = data

        except Exception as e:

            results[table] = (
                f"Error reading table: {str(e)}"
            )

    conn.close()

    return results


def customer_exists(customer_id):

    conn = get_connection()

    try:

        result = pd.read_sql_query(
            """
            SELECT COUNT(*) AS count
            FROM customers
            WHERE customer_id = ?
            """,
            conn,
            params=(customer_id,)
        )

        exists = result.iloc[0]["count"] > 0

    except Exception:

        exists = False

    conn.close()

    return exists


print("CRM backend loaded successfully")
'''

with open(
    BACKEND_PATH,
    "w",
    encoding="utf-8"
) as f:

    f.write(backend_code)

print("✅ CRM backend created")
print(BACKEND_PATH)

✅ CRM backend created
/content/crm_backend.py

In [125]:
# ============================================
# CELL 105 — TEST CRM BACKEND
# ============================================

import sys

if "/content" not in sys.path:
    sys.path.append("/content")

from crm_backend import (
    get_database_tables,
    get_customer_data,
    customer_exists
)

print("📦 Database Tables:")
print(get_database_tables())

# Get first real customer ID
conn = sqlite3.connect(
    "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"
)

test_customer = pd.read_sql_query(
    """
    SELECT customer_id
    FROM customers
    LIMIT 1
    """,
    conn
).iloc[0]["customer_id"]

conn.close()

print("\n👤 Test Customer:", test_customer)

print(
    "Customer exists:",
    customer_exists(test_customer)
)

customer_data = get_customer_data(
    test_customer
)

print("\n📊 Retrieved CRM Data:")

for table, data in customer_data.items():

    print("\n" + "=" * 50)
    print("TABLE:", table)
    print("=" * 50)

    if isinstance(data, pd.DataFrame):
        print("Records:", len(data))
        display(data.head())
    else:
        print(data)

CRM backend loaded successfully
📦 Database Tables:
['customers', 'messages', 'raw_conversations', 'support_tickets']

👤 Test Customer: CUST100000
Customer exists: True

📊 Retrieved CRM Data:

==================================================
TABLE: customers
==================================================
Records: 1

,customer_id,conv_id,industry,most_recent_product,first_contact,last_contact,total_interactions
0,CUST100000,C0000001,SaaS,SSO,2025-08-02T17:36:00,2025-08-06T04:39:00,12

In [126]:
# ============================================
# CELL 106 — INSPECT ANALYTICS COLUMNS
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"

conn = sqlite3.connect(DB_PATH)

tables = [
    "customers",
    "messages",
    "raw_conversations",
    "support_tickets"
]

for table in tables:

    print("\n" + "=" * 60)
    print(f"📊 {table.upper()} COLUMNS")
    print("=" * 60)

    schema = pd.read_sql_query(
        f"PRAGMA table_info({table})",
        conn
    )

    print(schema[["name", "type"]].to_string(index=False))

conn.close()

============================================================
📊 CUSTOMERS COLUMNS
============================================================
               name    type
        customer_id    TEXT
            conv_id    TEXT
           industry    TEXT
most_recent_product    TEXT
      first_contact    TEXT
       last_contact    TEXT
 total_interactions INTEGER

============================================================
📊 MESSAGES COLUMNS
============================================================
             name    type
          conv_id    TEXT
       turn_index INTEGER
             role    TEXT
             text    TEXT
        timestamp    TEXT
         industry    TEXT
          product    TEXT
       issue_type    TEXT
         language    TEXT
          channel    TEXT
    customer_name    TEXT
       agent_name    TEXT
overall_sentiment    TEXT
  overall_urgency    TEXT
          outcome    TEXT
   primary_intent    TEXT

============================================================
📊 RAW_CONVERSATIONS COLUMNS
============================================================
             name    type
          conv_id    TEXT
       turn_index INTEGER
             role    TEXT
             text    TEXT
        timestamp    TEXT
         industry    TEXT
          product    TEXT
       issue_type    TEXT
         language    TEXT
          channel    TEXT
    customer_name    TEXT
       agent_name    TEXT
overall_sentiment    TEXT
  overall_urgency    TEXT
          outcome    TEXT
   primary_intent    TEXT

============================================================
📊 SUPPORT_TICKETS COLUMNS
============================================================
         name      type
    ticket_id      TEXT
      conv_id      TEXT
     industry      TEXT
      product      TEXT
   issue_type      TEXT
     priority      TEXT
       status      TEXT
   started_at TIMESTAMP
last_activity TIMESTAMP
message_count   INTEGER

In [127]:
# ============================================
# CELL 106 — INSPECT DATABASE COLUMNS
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"

conn = sqlite3.connect(DB_PATH)

tables = [
    "customers",
    "messages",
    "raw_conversations",
    "support_tickets"
]

for table in tables:

    print("\n" + "=" * 60)
    print(f"📊 {table.upper()}")
    print("=" * 60)

    schema = pd.read_sql_query(
        f"PRAGMA table_info({table})",
        conn
    )

    print(schema[["name", "type"]].to_string(index=False))

conn.close()

============================================================
📊 CUSTOMERS
============================================================
               name    type
        customer_id    TEXT
            conv_id    TEXT
           industry    TEXT
most_recent_product    TEXT
      first_contact    TEXT
       last_contact    TEXT
 total_interactions INTEGER

============================================================
📊 MESSAGES
============================================================
             name    type
          conv_id    TEXT
       turn_index INTEGER
             role    TEXT
             text    TEXT
        timestamp    TEXT
         industry    TEXT
          product    TEXT
       issue_type    TEXT
         language    TEXT
          channel    TEXT
    customer_name    TEXT
       agent_name    TEXT
overall_sentiment    TEXT
  overall_urgency    TEXT
          outcome    TEXT
   primary_intent    TEXT

============================================================
📊 RAW_CONVERSATIONS
============================================================
             name    type
          conv_id    TEXT
       turn_index INTEGER
             role    TEXT
             text    TEXT
        timestamp    TEXT
         industry    TEXT
          product    TEXT
       issue_type    TEXT
         language    TEXT
          channel    TEXT
    customer_name    TEXT
       agent_name    TEXT
overall_sentiment    TEXT
  overall_urgency    TEXT
          outcome    TEXT
   primary_intent    TEXT

============================================================
📊 SUPPORT_TICKETS
============================================================
         name      type
    ticket_id      TEXT
      conv_id      TEXT
     industry      TEXT
      product      TEXT
   issue_type      TEXT
     priority      TEXT
       status      TEXT
   started_at TIMESTAMP
last_activity TIMESTAMP
message_count   INTEGER

In [128]:
# ============================================
# CELL 107 — UPGRADED ANALYTICS DASHBOARD
# ============================================

APP_PATH = "/content/agentic_crm_app.py"

app_code = r'''
import streamlit as st
import sqlite3
import pandas as pd
import os

# ============================================
# CONFIG
# ============================================

st.set_page_config(
    page_title="Agentic AI CRM",
    page_icon="🤖",
    layout="wide"
)

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"


# ============================================
# DATABASE
# ============================================

@st.cache_resource
def get_connection():
    return sqlite3.connect(
        DB_PATH,
        check_same_thread=False
    )


@st.cache_data(ttl=60)
def run_query(query):
    conn = get_connection()
    return pd.read_sql_query(query, conn)


conn = get_connection()


# ============================================
# SIDEBAR
# ============================================

st.sidebar.title("🤖 Agentic AI CRM")

st.sidebar.markdown(
    "### AI-Powered Customer Support Platform"
)

st.sidebar.divider()

page = st.sidebar.radio(
    "Navigation",
    [
        "📊 Dashboard",
        "👥 Customers",
        "🎫 Support Tickets",
        "💬 AI Support",
        "📚 Knowledge Base",
        "🤖 Agent Activity"
    ]
)

st.sidebar.divider()

st.sidebar.success("🟢 System Online")

st.sidebar.caption(
    "Agentic AI + RAG + CRM Analytics"
)


# ============================================
# DASHBOARD
# ============================================

if page == "📊 Dashboard":

    st.title("📊 CRM Analytics Dashboard")

    st.caption(
        "Real-time insights from Customer Support Data"
    )

    # ----------------------------------------
    # KPI DATA
    # ----------------------------------------

    customers = run_query(
        "SELECT COUNT(*) AS count FROM customers"
    ).iloc[0]["count"]

    tickets = run_query(
        "SELECT COUNT(*) AS count FROM support_tickets"
    ).iloc[0]["count"]

    conversations = run_query(
        "SELECT COUNT(DISTINCT conv_id) AS count FROM raw_conversations"
    ).iloc[0]["count"]

    messages = run_query(
        "SELECT COUNT(*) AS count FROM messages"
    ).iloc[0]["count"]

    # ----------------------------------------
    # KPI CARDS
    # ----------------------------------------

    col1, col2, col3, col4 = st.columns(4)

    col1.metric(
        "👥 Total Customers",
        f"{customers:,}"
    )

    col2.metric(
        "🎫 Support Tickets",
        f"{tickets:,}"
    )

    col3.metric(
        "💬 Conversations",
        f"{conversations:,}"
    )

    col4.metric(
        "📨 Total Messages",
        f"{messages:,}"
    )

    st.divider()


    # ========================================
    # TICKET ANALYTICS
    # ========================================

    st.subheader("🎫 Support Ticket Analytics")

    col1, col2 = st.columns(2)

    # ----------------------------------------
    # TICKET STATUS
    # ----------------------------------------

    with col1:

        status_df = run_query(
            """
            SELECT
                status,
                COUNT(*) AS ticket_count
            FROM support_tickets
            GROUP BY status
            ORDER BY ticket_count DESC
            """
        )

        st.markdown("#### 📊 Tickets by Status")

        st.bar_chart(
            status_df.set_index("status")
        )


    # ----------------------------------------
    # PRIORITY
    # ----------------------------------------

    with col2:

        priority_df = run_query(
            """
            SELECT
                priority,
                COUNT(*) AS ticket_count
            FROM support_tickets
            GROUP BY priority
            ORDER BY ticket_count DESC
            """
        )

        st.markdown("#### 🔥 Ticket Priority Distribution")

        st.bar_chart(
            priority_df.set_index("priority")
        )


    st.divider()


    # ========================================
    # ISSUE + INDUSTRY ANALYTICS
    # ========================================

    col1, col2 = st.columns(2)

    # ----------------------------------------
    # ISSUE TYPES
    # ----------------------------------------

    with col1:

        issue_df = run_query(
            """
            SELECT
                issue_type,
                COUNT(*) AS ticket_count
            FROM support_tickets
            GROUP BY issue_type
            ORDER BY ticket_count DESC
            LIMIT 10
            """
        )

        st.markdown("#### 🛠️ Top Support Issues")

        st.bar_chart(
            issue_df.set_index("issue_type")
        )


    # ----------------------------------------
    # INDUSTRIES
    # ----------------------------------------

    with col2:

        industry_df = run_query(
            """
            SELECT
                industry,
                COUNT(*) AS ticket_count
            FROM support_tickets
            GROUP BY industry
            ORDER BY ticket_count DESC
            LIMIT 10
            """
        )

        st.markdown("#### 🏢 Tickets by Industry")

        st.bar_chart(
            industry_df.set_index("industry")
        )


    st.divider()


    # ========================================
    # AI CUSTOMER INSIGHTS
    # ========================================

    st.subheader("🧠 AI Customer Insights")

    col1, col2, col3 = st.columns(3)


    # ----------------------------------------
    # SENTIMENT
    # ----------------------------------------

    with col1:

        sentiment_df = run_query(
            """
            SELECT
                overall_sentiment,
                COUNT(*) AS message_count
            FROM messages
            WHERE overall_sentiment IS NOT NULL
            GROUP BY overall_sentiment
            ORDER BY message_count DESC
            """
        )

        st.markdown("#### 😊 Customer Sentiment")

        st.bar_chart(
            sentiment_df.set_index(
                "overall_sentiment"
            )
        )


    # ----------------------------------------
    # URGENCY
    # ----------------------------------------

    with col2:

        urgency_df = run_query(
            """
            SELECT
                overall_urgency,
                COUNT(*) AS message_count
            FROM messages
            WHERE overall_urgency IS NOT NULL
            GROUP BY overall_urgency
            ORDER BY message_count DESC
            """
        )

        st.markdown("#### ⚠️ Customer Urgency")

        st.bar_chart(
            urgency_df.set_index(
                "overall_urgency"
            )
        )


    # ----------------------------------------
    # CHANNEL
    # ----------------------------------------

    with col3:

        channel_df = run_query(
            """
            SELECT
                channel,
                COUNT(*) AS message_count
            FROM messages
            WHERE channel IS NOT NULL
            GROUP BY channel
            ORDER BY message_count DESC
            """
        )

        st.markdown("#### 📱 Support Channels")

        st.bar_chart(
            channel_df.set_index(
                "channel"
            )
        )


    st.divider()


    # ========================================
    # TICKETS OVER TIME
    # ========================================

    st.subheader("📈 Support Activity Over Time")

    activity_df = run_query(
        """
        SELECT
            DATE(started_at) AS date,
            COUNT(*) AS ticket_count
        FROM support_tickets
        WHERE started_at IS NOT NULL
        GROUP BY DATE(started_at)
        ORDER BY date
        """
    )

    if not activity_df.empty:

        activity_df["date"] = pd.to_datetime(
            activity_df["date"]
        )

        activity_df = activity_df.set_index(
            "date"
        )

        st.line_chart(
            activity_df["ticket_count"]
        )

    else:

        st.info(
            "No timestamp data available for ticket activity."
        )


    st.divider()


    # ========================================
    # RECENT TICKETS
    # ========================================

    st.subheader("📋 Recent Support Tickets")

    recent_tickets = run_query(
        """
        SELECT
            ticket_id,
            conv_id,
            industry,
            product,
            issue_type,
            priority,
            status,
            started_at,
            last_activity,
            message_count
        FROM support_tickets
        ORDER BY last_activity DESC
        LIMIT 20
        """
    )

    st.dataframe(
        recent_tickets,
        use_container_width=True,
        hide_index=True
    )


# ============================================
# CUSTOMERS PAGE
# ============================================

elif page == "👥 Customers":

    st.title("👥 Customer Management")

    search = st.text_input(
        "🔍 Search Customer ID",
        placeholder="Example: CUST10001"
    )

    if search:

        query = """
        SELECT *
        FROM customers
        WHERE customer_id LIKE ?
        LIMIT 100
        """

        df = pd.read_sql_query(
            query,
            conn,
            params=(f"%{search}%",)
        )

    else:

        df = run_query(
            """
            SELECT *
            FROM customers
            LIMIT 100
            """
        )

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True
    )


# ============================================
# SUPPORT TICKETS PAGE
# ============================================

elif page == "🎫 Support Tickets":

    st.title("🎫 Support Ticket Management")

    col1, col2 = st.columns(2)

    with col1:
        status_filter = st.selectbox(
            "Filter by Status",
            ["All"] +
            run_query(
                """
                SELECT DISTINCT status
                FROM support_tickets
                WHERE status IS NOT NULL
                """
            )["status"].tolist()
        )

    with col2:
        priority_filter = st.selectbox(
            "Filter by Priority",
            ["All"] +
            run_query(
                """
                SELECT DISTINCT priority
                FROM support_tickets
                WHERE priority IS NOT NULL
                """
            )["priority"].tolist()
        )


    query = "SELECT * FROM support_tickets WHERE 1=1"

    if status_filter != "All":
        query += f" AND status = '{status_filter}'"

    if priority_filter != "All":
        query += f" AND priority = '{priority_filter}'"

    query += " LIMIT 500"

    df = run_query(query)

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True
    )


# ============================================
# AI SUPPORT
# ============================================

elif page == "💬 AI Support":

    st.title("💬 AI Customer Support")

    st.write(
        "Ask the Agentic AI system about a customer."
    )

    customer_id = st.text_input(
        "Customer ID",
        placeholder="Example: CUST10001"
    )

    question = st.text_area(
        "Customer Support Question",
        placeholder="Example: Should this customer be escalated?"
    )

    if st.button(
        "🤖 Ask AI",
        type="primary"
    ):

        if not customer_id or not question:

            st.warning(
                "Please enter both Customer ID and your question."
            )

        else:

            st.info(
                "🤖 Agentic AI integration will be connected next."
            )

            st.write(
                f"**Customer ID:** {customer_id}"
            )

            st.write(
                f"**Question:** {question}"
            )


# ============================================
# KNOWLEDGE BASE
# ============================================

elif page == "📚 Knowledge Base":

    st.title("📚 RAG Knowledge Base")

    documents_path = (
        "/content/drive/MyDrive/"
        "Agentic_AI_CRM/data/documents"
    )

    if os.path.exists(documents_path):

        files = os.listdir(documents_path)

        if files:

            for file in files:
                st.write(f"📄 {file}")

        else:
            st.info(
                "No documents found."
            )

    else:

        st.warning(
            "Knowledge base directory not found."
        )


# ============================================
# AGENT ACTIVITY
# ============================================

elif page == "🤖 Agent Activity":

    st.title("🤖 Multi-Agent Activity")

    st.markdown(
        """
        ### Agentic AI Workflow

        🔵 **Supervisor Agent**
        Decides which agent should handle the request.

        🟢 **CRM Agent**
        Retrieves customer and support data.

        🟡 **RAG Agent**
        Searches the company knowledge base.

        🟠 **Support Agent**
        Analyzes the customer problem.

        🔴 **Escalation Agent**
        Determines whether escalation is required.

        🟣 **Response Agent**
        Generates the final customer response.
        """
    )

    st.info(
        "Agent activity logs will be connected to the live LangGraph workflow next."
    )
'''

with open(
    APP_PATH,
    "w",
    encoding="utf-8"
) as f:
    f.write(app_code)

print("✅ Advanced analytics dashboard created successfully!")

✅ Advanced analytics dashboard created successfully!

In [129]:
# ============================================
# CELL 108 — RESTART STREAMLIT
# ============================================

import os
import subprocess
import time

os.system("pkill -f streamlit")

time.sleep(3)

streamlit_process = subprocess.Popen(
    [
        "streamlit",
        "run",
        APP_PATH,
        "--server.port",
        "8501",
        "--server.address",
        "0.0.0.0"
    ]
)

time.sleep(5)

print("🚀 Streamlit dashboard restarted!")

WARNING:pyngrok.process.ngrok:t=2026-08-29T11:23:25+0000 lvl=warn msg="failed to open private leg" id=05721f6de963 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-29T11:23:25+0000 lvl=warn msg="failed to open private leg" id=69d45013cebe privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-29T11:23:26+0000 lvl=warn msg="failed to open private leg" id=768596f8f7f4 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-29T11:23:26+0000 lvl=warn msg="failed to open private leg" id=de61fa874c59 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-29T11:23:28+0000 lvl=warn msg="failed to open private leg" id=883dd40a1dd3 privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"
WARNING:pyngrok.process.ngrok:t=2026-08-29T11:23:28+0000 lvl=warn msg="failed to open private leg" id=05899e3fcf0e privaddr=localhost:8501 err="dial tcp [::1]:8501: connect: connection refused"

🚀 Streamlit dashboard restarted!

In [130]:
from pyngrok import ngrok

ngrok.kill()

public_url = ngrok.connect(8501)

print("🌐 WEBSITE URL:")
print(public_url)

🌐 WEBSITE URL:
NgrokTunnel: "https://arousal-cause-chill.ngrok-free.dev" -> "http://localhost:8501"

In [134]:
print(APP_PATH)

/content/agentic_crm_app.py

In [136]:
import os

print("App exists:", os.path.exists("/content/agentic_crm_app.py"))

App exists: True

In [137]:
!ps aux | grep streamlit

root       14041  4.4  1.7 1624652 237744 ?      Sl   11:23   0:22 /usr/bin/python3 /usr/local/bin/streamlit run /content/agentic_crm_app.py --server.port 8501 --server.address 0.0.0.0
root       16208  0.0  0.0   7372  3428 ?        S    11:32   0:00 /bin/bash -c ps aux | grep streamlit
root       16210  0.0  0.0   6480  2352 ?        S    11:32   0:00 grep streamlit

In [138]:
import subprocess
import time

APP_PATH = "/content/agentic_crm_app.py"

streamlit_process = subprocess.Popen([
    "streamlit",
    "run",
    APP_PATH,
    "--server.port", "8501",
    "--server.address", "0.0.0.0"
])

time.sleep(8)

print("🚀 Streamlit started")

🚀 Streamlit started

In [139]:
from pyngrok import ngrok

# Close old tunnels only
ngrok.kill()

time.sleep(2)

public_url = ngrok.connect(8501)

print("🌐 OPEN THIS NEW URL:")
print(public_url)

🌐 OPEN THIS NEW URL:
NgrokTunnel: "https://arousal-cause-chill.ngrok-free.dev" -> "http://localhost:8501"

In [141]:
# ============================================
#  ADD ADVANCED KPIs + ALERT CENTER
# ============================================

APP_PATH = "/content/agentic_crm_app.py"

with open(APP_PATH, "r", encoding="utf-8") as f:
    app_code = f.read()

# This code will be added before the first
# dashboard divider after KPI cards
advanced_section = '''
    # ========================================
    # ADVANCED KPI INSIGHTS
    # ========================================

    st.subheader("🎯 Advanced Support Insights")

    high_priority = run_query(
        """
        SELECT COUNT(*) AS count
        FROM support_tickets
        WHERE LOWER(priority) IN ('high', 'urgent', 'critical')
        """
    ).iloc[0]["count"]

    open_tickets = run_query(
        """
        SELECT COUNT(*) AS count
        FROM support_tickets
        WHERE LOWER(status) NOT IN ('closed', 'resolved')
        """
    ).iloc[0]["count"]

    negative_sentiment = run_query(
        """
        SELECT COUNT(*) AS count
        FROM messages
        WHERE LOWER(overall_sentiment)
        IN ('negative', 'very negative')
        """
    ).iloc[0]["count"]

    urgent_messages = run_query(
        """
        SELECT COUNT(*) AS count
        FROM messages
        WHERE LOWER(overall_urgency)
        IN ('high', 'urgent', 'critical')
        """
    ).iloc[0]["count"]

    avg_messages = round(
        messages / conversations,
        2
    ) if conversations > 0 else 0


    col1, col2, col3, col4 = st.columns(4)

    col1.metric(
        "🔴 High Priority",
        f"{high_priority:,}"
    )

    col2.metric(
        "📂 Open Tickets",
        f"{open_tickets:,}"
    )

    col3.metric(
        "😞 Negative Sentiment",
        f"{negative_sentiment:,}"
    )

    col4.metric(
        "⚡ Avg Msg / Conversation",
        avg_messages
    )


    # ========================================
    # CRITICAL ALERT CENTER
    # ========================================

    st.divider()

    st.subheader("🚨 Critical Alert Center")

    alert1, alert2, alert3 = st.columns(3)

    with alert1:

        if high_priority > 0:

            st.error(
                f"🔴 {high_priority:,} high-priority tickets need attention."
            )

        else:

            st.success(
                "✅ No high-priority tickets."
            )


    with alert2:

        if urgent_messages > 0:

            st.warning(
                f"⚠️ {urgent_messages:,} urgent customer messages detected."
            )

        else:

            st.success(
                "✅ No urgent customer messages."
            )


    with alert3:

        if negative_sentiment > 0:

            st.error(
                f"😞 {negative_sentiment:,} negative sentiment messages detected."
            )

        else:

            st.success(
                "😊 No negative sentiment alerts."
            )


'''

# Find the KPI card section and insert after it
marker = '    st.divider()\n\n\n    # ========================================\n    # TICKET ANALYTICS'

if marker in app_code:
    app_code = app_code.replace(
        marker,
        advanced_section + marker,
        1
    )

    with open(APP_PATH, "w", encoding="utf-8") as f:
        f.write(app_code)

    print("✅ Advanced KPIs and Critical Alert Center added!")
else:
    print("❌ Could not find the dashboard insertion point.")
    print("Please do not run any 'if page ==' code directly in Colab.")

✅ Advanced KPIs and Critical Alert Center added!

In [142]:
# ============================================
#  CRM ANALYTICS TOOL
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"


def get_crm_summary():

    conn = sqlite3.connect(DB_PATH)

    summary = {}

    summary["total_customers"] = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM customers",
        conn
    ).iloc[0]["count"]

    summary["total_tickets"] = pd.read_sql_query(
        "SELECT COUNT(*) AS count FROM support_tickets",
        conn
    ).iloc[0]["count"]

    summary["high_priority_tickets"] = pd.read_sql_query(
        """
        SELECT COUNT(*) AS count
        FROM support_tickets
        WHERE LOWER(priority)
        IN ('high', 'urgent', 'critical')
        """,
        conn
    ).iloc[0]["count"]

    summary["open_tickets"] = pd.read_sql_query(
        """
        SELECT COUNT(*) AS count
        FROM support_tickets
        WHERE LOWER(status)
        NOT IN ('closed', 'resolved')
        """,
        conn
    ).iloc[0]["count"]

    summary["negative_sentiment"] = pd.read_sql_query(
        """
        SELECT COUNT(*) AS count
        FROM messages
        WHERE LOWER(overall_sentiment)
        IN ('negative', 'very negative')
        """,
        conn
    ).iloc[0]["count"]

    conn.close()

    return summary


crm_summary = get_crm_summary()

print("📊 CRM SUMMARY")
print("=" * 40)

for key, value in crm_summary.items():
    print(f"{key}: {value:,}")

📊 CRM SUMMARY
========================================
total_customers: 69,731
total_tickets: 69,731
high_priority_tickets: 0
open_tickets: 69,731
negative_sentiment: 487,949

In [143]:
crm_summary = get_crm_summary()

crm_summary

{'total_customers': np.int64(69731),
 'total_tickets': np.int64(69731),
 'high_priority_tickets': np.int64(0),
 'open_tickets': np.int64(69731),
 'negative_sentiment': np.int64(487949)}

In [144]:
# ============================================
# CRM QUESTION ANSWER TOOL
# ============================================

import sqlite3
import pandas as pd

DB_PATH = "/content/drive/MyDrive/Agentic_AI_CRM/database/crm.db"


def ask_crm(question):

    question_lower = question.lower()

    conn = sqlite3.connect(DB_PATH)

    try:

        # ------------------------------------
        # TOTAL CUSTOMERS
        # ------------------------------------

        if "customer" in question_lower and (
            "how many" in question_lower or
            "total" in question_lower
        ):

            count = pd.read_sql_query(
                "SELECT COUNT(*) AS count FROM customers",
                conn
            ).iloc[0]["count"]

            return f"👥 Total customers: {count:,}"


        # ------------------------------------
        # HIGH PRIORITY TICKETS
        # ------------------------------------

        elif (
            "high priority" in question_lower or
            "critical ticket" in question_lower
        ):

            count = pd.read_sql_query(
                """
                SELECT COUNT(*) AS count
                FROM support_tickets
                WHERE LOWER(priority)
                IN ('high', 'urgent', 'critical')
                """,
                conn
            ).iloc[0]["count"]

            return (
                f"🔴 High-priority tickets: {count:,}"
            )


        # ------------------------------------
        # OPEN TICKETS
        # ------------------------------------

        elif "open ticket" in question_lower:

            count = pd.read_sql_query(
                """
                SELECT COUNT(*) AS count
                FROM support_tickets
                WHERE LOWER(status)
                NOT IN ('closed', 'resolved')
                """,
                conn
            ).iloc[0]["count"]

            return f"📂 Open tickets: {count:,}"


        # ------------------------------------
        # TOP ISSUES
        # ------------------------------------

        elif (
            "top issue" in question_lower or
            "most common issue" in question_lower or
            "biggest problem" in question_lower
        ):

            df = pd.read_sql_query(
                """
                SELECT
                    issue_type,
                    COUNT(*) AS count
                FROM support_tickets
                GROUP BY issue_type
                ORDER BY count DESC
                LIMIT 5
                """,
                conn
            )

            result = "🛠️ Top Support Issues:\n\n"

            for _, row in df.iterrows():

                result += (
                    f"• {row['issue_type']}: "
                    f"{row['count']:,} tickets\n"
                )

            return result


        # ------------------------------------
        # TOP INDUSTRY
        # ------------------------------------

        elif (
            "industry" in question_lower and
            (
                "most" in question_lower or
                "highest" in question_lower
            )
        ):

            df = pd.read_sql_query(
                """
                SELECT
                    industry,
                    COUNT(*) AS count
                FROM support_tickets
                GROUP BY industry
                ORDER BY count DESC
                LIMIT 1
                """,
                conn
            )

            if not df.empty:

                return (
                    f"🏢 Industry with the most tickets: "
                    f"{df.iloc[0]['industry']} "
                    f"({df.iloc[0]['count']:,} tickets)"
                )


        # ------------------------------------
        # NEGATIVE SENTIMENT
        # ------------------------------------

        elif (
            "negative sentiment" in question_lower or
            "negative customer" in question_lower
        ):

            count = pd.read_sql_query(
                """
                SELECT COUNT(*) AS count
                FROM messages
                WHERE LOWER(overall_sentiment)
                IN ('negative', 'very negative')
                """,
                conn
            ).iloc[0]["count"]

            return (
                f"😞 Negative sentiment messages: "
                f"{count:,}"
            )


        # ------------------------------------
        # DEFAULT
        # ------------------------------------

        else:

            return (
                "🤖 I understand your CRM question, "
                "but this question type is not connected yet. "
                "Next we will connect Gemini AI so you can "
                "ask natural language questions."
            )

    except Exception as e:

        return f"❌ Error: {str(e)}"

    finally:

        conn.close()


print("✅ CRM Question Tool created successfully!")

✅ CRM Question Tool created successfully!

In [145]:
# ============================================
# TEST CRM QUESTIONS
# ============================================

questions = [
    "How many customers are there?",
    "How many high priority tickets are there?",
    "What are the top issues?",
    "Which industry has the most tickets?",
    "How many negative sentiment messages are there?"
]

for question in questions:

    print("\n❓", question)
    print("🤖", ask_crm(question))
    print("-" * 50)

❓ How many customers are there?
🤖 👥 Total customers: 69,731
--------------------------------------------------

❓ How many high priority tickets are there?
🤖 🔴 High-priority tickets: 0
--------------------------------------------------

❓ What are the top issues?
🤖 🛠️ Top Support Issues:

• Service Not Activated: 4,723 tickets
• Technical Bug: 4,706 tickets
• Payment Failure: 4,699 tickets
• Late Delivery: 4,667 tickets
• Account Locked: 4,666 tickets

--------------------------------------------------

❓ Which industry has the most tickets?
🤖 🏢 Industry with the most tickets: Telecom (8,773 tickets)
--------------------------------------------------

❓ How many negative sentiment messages are there?
🤖 😞 Negative sentiment messages: 487,949
--------------------------------------------------

In [146]:
# ============================================
# ADD CRM AI PAGE TO STREAMLIT
# ============================================

APP_PATH = "/content/agentic_crm_app.py"

with open(APP_PATH, "r", encoding="utf-8") as f:
    app_code = f.read()

# Add new navigation page
app_code = app_code.replace(
    '"🤖 Agent Activity"',
    '"🤖 Agent Activity",\n        "✨ Ask CRM AI"',
    1
)

# Add Ask CRM AI page at the end
ai_page_code = r'''

# ============================================
# ASK CRM AI
# ============================================

elif page == "✨ Ask CRM AI":

    st.title("✨ Ask AI About Your CRM")

    st.write(
        "Ask questions about customers, tickets, issues, and support analytics."
    )

    st.markdown("### 💡 Try asking:")

    st.write("""
    • How many customers are there?
    • How many high priority tickets are there?
    • What are the top issues?
    • Which industry has the most tickets?
    • How many negative sentiment messages are there?
    """)

    question = st.text_area(
        "Ask your CRM AI",
        placeholder="Example: What are the biggest customer problems?"
    )

    if st.button("✨ Ask AI", type="primary"):

        if not question.strip():

            st.warning("Please enter a question.")

        else:

            with st.spinner("🤖 Analyzing CRM data..."):

                question_lower = question.lower()

                try:

                    if "customer" in question_lower and (
                        "how many" in question_lower or
                        "total" in question_lower
                    ):

                        result = run_query(
                            "SELECT COUNT(*) AS count FROM customers"
                        )

                        answer = (
                            f"👥 Total customers: "
                            f"{result.iloc[0]['count']:,}"
                        )


                    elif (
                        "high priority" in question_lower or
                        "critical ticket" in question_lower
                    ):

                        result = run_query(
                            """
                            SELECT COUNT(*) AS count
                            FROM support_tickets
                            WHERE LOWER(priority)
                            IN ('high', 'urgent', 'critical')
                            """
                        )

                        answer = (
                            f"🔴 High-priority tickets: "
                            f"{result.iloc[0]['count']:,}"
                        )


                    elif "open ticket" in question_lower:

                        result = run_query(
                            """
                            SELECT COUNT(*) AS count
                            FROM support_tickets
                            WHERE LOWER(status)
                            NOT IN ('closed', 'resolved')
                            """
                        )

                        answer = (
                            f"📂 Open tickets: "
                            f"{result.iloc[0]['count']:,}"
                        )


                    elif (
                        "top issue" in question_lower or
                        "most common issue" in question_lower or
                        "biggest problem" in question_lower
                    ):

                        result = run_query(
                            """
                            SELECT
                                issue_type,
                                COUNT(*) AS count
                            FROM support_tickets
                            GROUP BY issue_type
                            ORDER BY count DESC
                            LIMIT 5
                            """
                        )

                        answer = "🛠️ Top Support Issues:\n\n"

                        for _, row in result.iterrows():

                            answer += (
                                f"• {row['issue_type']}: "
                                f"{row['count']:,} tickets\n"
                            )


                    elif (
                        "industry" in question_lower and
                        ("most" in question_lower or
                         "highest" in question_lower)
                    ):

                        result = run_query(
                            """
                            SELECT
                                industry,
                                COUNT(*) AS count
                            FROM support_tickets
                            GROUP BY industry
                            ORDER BY count DESC
                            LIMIT 1
                            """
                        )

                        answer = (
                            f"🏢 Industry with the most tickets: "
                            f"{result.iloc[0]['industry']} "
                            f"({result.iloc[0]['count']:,} tickets)"
                        )


                    elif (
                        "negative sentiment" in question_lower or
                        "negative customer" in question_lower
                    ):

                        result = run_query(
                            """
                            SELECT COUNT(*) AS count
                            FROM messages
                            WHERE LOWER(overall_sentiment)
                            IN ('negative', 'very negative')
                            """
                        )

                        answer = (
                            f"😞 Negative sentiment messages: "
                            f"{result.iloc[0]['count']:,}"
                        )


                    else:

                        answer = (
                            "🤖 I can currently answer questions about "
                            "customers, high-priority tickets, open tickets, "
                            "top issues, industries, and negative sentiment. "
                            "Next, Gemini AI will make this assistant fully "
                            "natural-language powered."
                        )


                    st.success("Analysis complete!")

                    st.markdown("### 🤖 AI Answer")

                    st.info(answer)

                except Exception as e:

                    st.error(f"Error: {str(e)}")
'''

# Append page only once
if 'elif page == "✨ Ask CRM AI":' not in app_code:
    app_code += ai_page_code

with open(APP_PATH, "w", encoding="utf-8") as f:
    f.write(app_code)

print("✅ Ask CRM AI page added successfully!")

✅ Ask CRM AI page added successfully!